//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALLFILESINFO
    {
        public decimal FILEID { get; set; }
        public string BIZCODE { get; set; }
        public string FILETYPECODE { get; set; }
        public string FILENAMEEN { get; set; }
        public string INSTITUTIONNAMEEN { get; set; }
        public string FILETYPENAME { get; set; }
        public string INSTITUTIONINFOCODE { get; set; }
        public string FILENAMECN { get; set; }
        public string EXTENSION { get; set; }
    }
}
