//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANK_FIN_PRD
    {
        public Nullable<int> SEQ { get; set; }
        public Nullable<System.DateTime> CTIME { get; set; }
        public Nullable<System.DateTime> MTIME { get; set; }
        public Nullable<short> ISVALID { get; set; }
        public Nullable<decimal> GENIUS_UID { get; set; }
        public int INNER_CODE { get; set; }
        public string PRD_NAME { get; set; }
        public Nullable<int> BANK_ID { get; set; }
        public string BANK_NAME { get; set; }
        public string PRD_SNAME { get; set; }
    }
}
