//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANK_FIN_PRD_PROSP
    {
        public long SEQ { get; set; }
        public System.DateTime CTIME { get; set; }
        public System.DateTime MTIME { get; set; }
        public short ISVALID { get; set; }
        public decimal GENIUS_UID { get; set; }
        public long INNER_CODE { get; set; }
        public string BANK_PRD_PROSP { get; set; }
        public string PRD_PROSP_MD5 { get; set; }
        public string ACCE_ROUTE { get; set; }
    }
}
