//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANK_FIN_DETAIL
    {
        public Nullable<int> SEQ { get; set; }
        public Nullable<System.DateTime> CTIME { get; set; }
        public Nullable<System.DateTime> MTIME { get; set; }
        public Nullable<short> ISVALID { get; set; }
        public Nullable<decimal> GENIUS_UID { get; set; }
        public int INNER_CODE { get; set; }
        public string PRD_SYS { get; set; }
        public Nullable<int> PRD_TYPE { get; set; }
        public string PRD_TYPE_NAME { get; set; }
        public Nullable<int> ENTR_MNG_TERM { get; set; }
        public Nullable<int> ENTR_MNG_UNIT { get; set; }
        public Nullable<System.DateTime> SELL_ORG_DATE { get; set; }
        public Nullable<System.DateTime> SELL_END_DATE { get; set; }
        public Nullable<System.DateTime> INC_ORG_DATE { get; set; }
        public Nullable<int> PAY_CYC { get; set; }
        public Nullable<int> PAY_CYC_UNIT { get; set; }
        public Nullable<decimal> PRD_MAX_YLD { get; set; }
        public Nullable<int> ENTR_CURNCY_TYPE { get; set; }
        public string ENTR_CURNCY_NAME { get; set; }
        public Nullable<int> ENTR_MIN_CURNCY { get; set; }
        public Nullable<int> CURNCY_INCR_UNIT { get; set; }
        public string MNG_COST { get; set; }
        public string IS_RETAIL { get; set; }
        public string IS_BNK_BRG_FRD { get; set; }
        public string IS_CST_BRG_FRD { get; set; }
        public string YLD_DET { get; set; }
        public string AD_TRM_CND { get; set; }
        public string AD_PRC_CND { get; set; }
        public string FEAT { get; set; }
        public string BNT_ACT { get; set; }
        public string SELL_ORG_DTL { get; set; }
        public string SELL_END_DTL { get; set; }
        public string RIST_WARE { get; set; }
        public string EXP_VIEW { get; set; }
        public string PRD_CODE { get; set; }
        public string ISS_AREA { get; set; }
        public string AC_ORG { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<int> INC_DATE { get; set; }
        public string RETN_TYPE { get; set; }
        public string IS_PLEDGE { get; set; }
        public string INC_CLA_BASIS { get; set; }
        public string AD_TRM_DATE_DTL { get; set; }
        public string CALL_DATE_DTL { get; set; }
        public string CURNCY_REC_DATE_DTL { get; set; }
        public string INV_OBJ { get; set; }
        public string TAX_REGL { get; set; }
        public Nullable<int> INV_TYPE { get; set; }
        public string INV_TYPE_DTL { get; set; }
        public Nullable<int> RIST_RTNG { get; set; }
        public string RIST_RTNG_DTL { get; set; }
        public Nullable<int> LIQ_RTNG { get; set; }
        public string LIQ_RTNG_DTL { get; set; }
        public Nullable<int> ISS_AREA_CODE { get; set; }
        public Nullable<decimal> MAT_ACTU_YLD { get; set; }
        public string IS_QDII { get; set; }
        public Nullable<int> HONOR_CAP_CURNCY_TYPE { get; set; }
        public string HONOR_CAP_CURNCY_NAME { get; set; }
        public Nullable<int> HONOR_INCM_CURNCY_TYPE { get; set; }
        public string HONOR_INCM_CURNCY_NAME { get; set; }
        public Nullable<int> INC_DATE_UNIT { get; set; }
        public Nullable<int> INV_UND_TYPE { get; set; }
        public Nullable<int> STRU_TYPE { get; set; }
        public Nullable<decimal> PRD_MIN_YLD { get; set; }
        public string TRM_DLY_REMARK { get; set; }
        public Nullable<decimal> PRD_MAX_YLD_L { get; set; }
        public Nullable<decimal> PLAN_SIZE_UP_LIM { get; set; }
        public Nullable<decimal> PLAN_SIZE_LOW_LIM { get; set; }
        public Nullable<int> IS_ROLL_PRO { get; set; }
        public Nullable<decimal> PRD_MAX_YLD_DE { get; set; }
        public Nullable<decimal> PRD_MAX_YLD_L_DE { get; set; }
        public string SELL_CHNL { get; set; }
        public Nullable<long> IS_PB { get; set; }
        public Nullable<long> ISS_OBJECT { get; set; }
        public string REGI_CODE { get; set; }
        public Nullable<int> OPERA_TYPE { get; set; }
    }
}
