//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANK_FIN_PRD_PROSP_DATA
    {
        public decimal INNER_CODE { get; set; }
        public System.DateTime CTIME { get; set; }
        public System.DateTime MTIME { get; set; }
        public string ACCE_ROUTE { get; set; }
        public Nullable<short> ISSYNCED { get; set; }
    }
}
