//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOND_BASIC_INFO
    {
        public long ID { get; set; }
        public Nullable<short> ISVALID { get; set; }
        public Nullable<System.DateTime> CCXEID { get; set; }
        public Nullable<long> BOND_ID { get; set; }
        public Nullable<long> BOND_UNI_CODE { get; set; }
        public string ISIN_CODE { get; set; }
        public string BOND_FULL_NAME { get; set; }
        public string BOND_CODE { get; set; }
        public string BOND_SHORT_NAME { get; set; }
        public string SPE_SHORT_NAME { get; set; }
        public string ENG_FULL_NAME { get; set; }
        public string ENG_SHORT_NAME { get; set; }
        public Nullable<decimal> BOND_MATU { get; set; }
        public Nullable<short> MATU_UNIT_PAR { get; set; }
        public Nullable<short> BOND_TYPE_PAR { get; set; }
        public Nullable<short> IS_TYPE_PAR { get; set; }
        public Nullable<System.DateTime> LIST_DATE { get; set; }
        public Nullable<short> SEC_MAR_PAR { get; set; }
        public Nullable<short> LIST_SECT_PAR { get; set; }
        public Nullable<short> LIST_STA_PAR { get; set; }
        public Nullable<short> ASE_LEVEL_PAR { get; set; }
        public Nullable<short> BOND_FORM_PAR { get; set; }
        public Nullable<short> ISS_STA_PAR { get; set; }
        public Nullable<short> IS_LIST_PAR { get; set; }
        public Nullable<short> IS_CROS_MAR_PAR { get; set; }
        public string PLEDGE_CODE { get; set; }
        public string PLEDGE_NAME { get; set; }
        public string CROS_MAR_DES { get; set; }
    }
}
