//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOND_RATE_INFO
    {
        public long ID { get; set; }
        public Nullable<short> ISVALID { get; set; }
        public Nullable<System.DateTime> CCXEID { get; set; }
        public Nullable<long> BOND_ID { get; set; }
        public Nullable<short> RATE_TYPE_PAR { get; set; }
        public Nullable<short> IS_SEGM_PAR { get; set; }
        public Nullable<short> INTE_PAY_CLS_PAR { get; set; }
        public Nullable<short> INTE_PAY_FREQ { get; set; }
        public Nullable<short> INTE_CALCU_CLS_PAR { get; set; }
        public Nullable<short> REPAY_CLS_PAY_PAR { get; set; }
        public Nullable<short> SIMP_COMP_INTE_PAR { get; set; }
        public Nullable<System.DateTime> INTE_START_DATE { get; set; }
        public Nullable<System.DateTime> ACTU_END_DATE { get; set; }
        public Nullable<System.DateTime> THEO_END_DATE { get; set; }
        public string YEAR_PAY_DATE { get; set; }
        public Nullable<System.DateTime> FIR_PAY_DATE { get; set; }
        public Nullable<decimal> ISS_COUP_RATE { get; set; }
        public Nullable<short> BASE_RATE_PAR { get; set; }
        public Nullable<System.DateTime> INIT_BASE_RATE_DATE { get; set; }
        public Nullable<decimal> BASE_RATE { get; set; }
        public Nullable<decimal> BAS_SPR { get; set; }
        public Nullable<decimal> OPT_EXTRA_SPR { get; set; }
        public Nullable<short> EXTRA_SPR_SEQ_NUM { get; set; }
        public Nullable<decimal> RATE_CEIL { get; set; }
        public Nullable<decimal> RATE_FLOOR { get; set; }
        public Nullable<short> IS_INTE_COMP_PAR { get; set; }
        public Nullable<decimal> COMP_RATE { get; set; }
        public Nullable<decimal> YTM_INTE_COMP { get; set; }
        public Nullable<decimal> REF_YIELD { get; set; }
        public string YEAR_PAY_MATU { get; set; }
        public Nullable<System.DateTime> MATU_PAY_DATE { get; set; }
        public string EXER_PAY_DATE { get; set; }
        public Nullable<decimal> PAY_FEE_RATE { get; set; }
        public string PAY_CLS_DES { get; set; }
        public string PAY_MATU { get; set; }
        public Nullable<decimal> NEW_COUP_RATE { get; set; }
    }
}
