//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOND
    {
        public string assetId { get; set; }
        public string bond_name_cn { get; set; }
        public string bond_name_en { get; set; }
        public string code { get; set; }
        public Nullable<decimal> amt_iss_tot { get; set; }
        public string coupon_class_cn { get; set; }
        public string coupon_class_en { get; set; }
        public string isfloat { get; set; }
        public string freq_cn { get; set; }
        public string freq_en { get; set; }
        public Nullable<decimal> orig_iss_cpn { get; set; }
        public Nullable<System.DateTime> orig_dated_dt { get; set; }
        public Nullable<System.DateTime> maturity_dt { get; set; }
        public Nullable<decimal> term { get; set; }
        public string BondTerm_cn { get; set; }
        public string BondTerm_en { get; set; }
        public Nullable<decimal> orig_avg_life { get; set; }
        public Nullable<decimal> bondterm_number { get; set; }
        public string float_index { get; set; }
        public Nullable<decimal> float_offset { get; set; }
        public string callorput_cn { get; set; }
        public string callorput_en { get; set; }
        public string isin_nm { get; set; }
        public string latest_rating_cd { get; set; }
        public Nullable<System.DateTime> orig_issue_dt { get; set; }
        public Nullable<decimal> orig_iss_amt { get; set; }
        public Nullable<decimal> yield { get; set; }
        public Nullable<decimal> orig_iss_px { get; set; }
        public Nullable<System.DateTime> listing_dt { get; set; }
        public string re_issue { get; set; }
        public string rating_number { get; set; }
        public string rating_src_cn { get; set; }
        public string rating_src_en { get; set; }
        public string party_rating_cd { get; set; }
        public string party_rating_number { get; set; }
        public string party_rating_src_cn { get; set; }
        public string party_rating_src_en { get; set; }
        public string cdc_asset_class_cn { get; set; }
        public string cdc_asset_class_en { get; set; }
        public string cdc_asset_class_cd { get; set; }
        public string ci_bond_flag { get; set; }
        public string provice_of_issuer_cn { get; set; }
        public string provice_of_issuer_en { get; set; }
        public string provice_of_issuer { get; set; }
        public Nullable<decimal> cdc_asset_class_number { get; set; }
        public string offer_registrant_name { get; set; }
        public Nullable<int> DayCountCd { get; set; }
        public string day_count_cn { get; set; }
        public string day_count_en { get; set; }
        public string seniority { get; set; }
        public string orig_iss_curr_cd { get; set; }
        public string exchange_name_cn { get; set; }
        public string exchange_name_en { get; set; }
        public string trustee_name_cn { get; set; }
        public string trustee_name_en { get; set; }
        public Nullable<decimal> PartyCntryIncorpCd { get; set; }
        public string PartyCntryIncorpDescr_cn { get; set; }
        public string PartyCntryIncorpDescr_en { get; set; }
        public string IssueCountryCd { get; set; }
        public string IssueCountry_cn { get; set; }
        public string IssueCountry_en { get; set; }
        public string IssuerInduSectorCd { get; set; }
        public string IssuerInduSectorCn { get; set; }
        public string IssuerInduSectorEn { get; set; }
    }
}
