//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOND_ISSER_INFO
    {
        public long ID { get; set; }
        public Nullable<short> ISVALID { get; set; }
        public Nullable<System.DateTime> CCXEID { get; set; }
        public Nullable<long> BOND_UNI_CODE { get; set; }
        public Nullable<long> ORG_UNI_CODE { get; set; }
        public Nullable<short> ISSER_TYPE_PAR { get; set; }
        public Nullable<System.DateTime> ISSER_CHAN_DATE { get; set; }
        public Nullable<short> IS_NEW_ISSER { get; set; }
    }
}
