//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOND_FIN_BALA_TABB
    {
        public long ID { get; set; }
        public Nullable<short> ISVALID { get; set; }
        public Nullable<System.DateTime> CCXEID { get; set; }
        public Nullable<long> COM_UNI_CODE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<short> SHEET_MARK_PAR { get; set; }
        public Nullable<short> SHEET_ATTR_PAR { get; set; }
        public Nullable<decimal> BS_01 { get; set; }
        public Nullable<decimal> BS_0101 { get; set; }
        public Nullable<decimal> BS_02 { get; set; }
        public Nullable<decimal> BS_03 { get; set; }
        public Nullable<decimal> BS_04 { get; set; }
        public Nullable<decimal> BS_05 { get; set; }
        public Nullable<decimal> BS_06 { get; set; }
        public Nullable<decimal> BS_07 { get; set; }
        public Nullable<decimal> BS_08 { get; set; }
        public Nullable<decimal> BS_09 { get; set; }
        public Nullable<decimal> BS_0901 { get; set; }
        public Nullable<decimal> BS_10 { get; set; }
        public Nullable<decimal> BS_11 { get; set; }
        public Nullable<decimal> BS_12 { get; set; }
        public Nullable<decimal> BS_13 { get; set; }
        public Nullable<decimal> BS_14 { get; set; }
        public Nullable<decimal> BS_15 { get; set; }
        public Nullable<decimal> BS_16 { get; set; }
        public Nullable<decimal> BS_17 { get; set; }
        public Nullable<decimal> BS_18 { get; set; }
        public Nullable<decimal> BS_19 { get; set; }
        public Nullable<decimal> BS_20 { get; set; }
        public Nullable<decimal> BS_21 { get; set; }
        public Nullable<decimal> BS_22 { get; set; }
        public Nullable<decimal> BS_23 { get; set; }
        public Nullable<decimal> BS_24 { get; set; }
        public Nullable<decimal> BS_25 { get; set; }
        public Nullable<decimal> BS_26 { get; set; }
        public Nullable<decimal> BS_27 { get; set; }
        public Nullable<decimal> BS_28 { get; set; }
        public Nullable<decimal> BS_29 { get; set; }
        public Nullable<decimal> BS_30 { get; set; }
        public Nullable<decimal> BS_31 { get; set; }
        public Nullable<decimal> BS_3101 { get; set; }
        public Nullable<decimal> BS_32 { get; set; }
        public Nullable<decimal> BS_33 { get; set; }
        public Nullable<decimal> BS_34 { get; set; }
        public Nullable<decimal> BS_35 { get; set; }
        public Nullable<decimal> BS_36 { get; set; }
        public Nullable<decimal> BS_37 { get; set; }
        public Nullable<decimal> BS_38 { get; set; }
        public Nullable<decimal> BS_39 { get; set; }
        public Nullable<decimal> BS_40 { get; set; }
        public Nullable<decimal> BS_4001 { get; set; }
        public Nullable<decimal> BS_41 { get; set; }
        public Nullable<decimal> BS_42 { get; set; }
        public Nullable<decimal> BS_43 { get; set; }
        public Nullable<decimal> BS_44 { get; set; }
        public Nullable<decimal> BS_45 { get; set; }
        public Nullable<decimal> BS_46 { get; set; }
        public Nullable<decimal> BS_47 { get; set; }
        public Nullable<decimal> BS_48 { get; set; }
        public Nullable<decimal> BS_49 { get; set; }
        public Nullable<decimal> BS_50 { get; set; }
        public Nullable<decimal> BS_51 { get; set; }
        public Nullable<decimal> BS_52 { get; set; }
        public Nullable<decimal> BS_53 { get; set; }
        public Nullable<decimal> BS_54 { get; set; }
        public Nullable<decimal> BS_55 { get; set; }
        public Nullable<decimal> BS_56 { get; set; }
        public Nullable<decimal> BS_57 { get; set; }
        public Nullable<decimal> BS_5701 { get; set; }
        public Nullable<decimal> BS_58 { get; set; }
        public Nullable<decimal> BS_59 { get; set; }
        public Nullable<decimal> BS_60 { get; set; }
        public Nullable<decimal> BS_61 { get; set; }
        public Nullable<decimal> BS_62 { get; set; }
        public Nullable<decimal> BS_63 { get; set; }
        public Nullable<decimal> BS_64 { get; set; }
        public Nullable<decimal> BS_65 { get; set; }
        public Nullable<decimal> BS_66 { get; set; }
        public Nullable<decimal> BS_67 { get; set; }
        public Nullable<decimal> BS_68 { get; set; }
        public Nullable<decimal> BS_69 { get; set; }
        public Nullable<decimal> BS_70 { get; set; }
        public Nullable<decimal> BS_71 { get; set; }
        public Nullable<decimal> BS_72 { get; set; }
        public Nullable<decimal> BS_73 { get; set; }
        public Nullable<decimal> BS_74 { get; set; }
        public Nullable<decimal> BS_75 { get; set; }
        public Nullable<decimal> BS_76 { get; set; }
        public Nullable<decimal> BS_77 { get; set; }
        public Nullable<decimal> BS_78 { get; set; }
        public Nullable<decimal> BS_79 { get; set; }
        public Nullable<decimal> BS_80 { get; set; }
        public Nullable<decimal> BS_81 { get; set; }
        public Nullable<decimal> BS_82 { get; set; }
        public Nullable<decimal> BS_83 { get; set; }
        public Nullable<decimal> BS_84 { get; set; }
        public Nullable<decimal> BS_85 { get; set; }
        public Nullable<decimal> BS_86 { get; set; }
        public Nullable<decimal> BS_87 { get; set; }
        public Nullable<decimal> BS_88 { get; set; }
        public Nullable<decimal> BS_89 { get; set; }
        public Nullable<decimal> BS_90 { get; set; }
        public Nullable<decimal> BS_91 { get; set; }
        public Nullable<decimal> BS_92 { get; set; }
        public Nullable<decimal> BS_93 { get; set; }
        public Nullable<decimal> BS_94 { get; set; }
        public Nullable<decimal> BS_95 { get; set; }
        public Nullable<decimal> BS_96 { get; set; }
        public Nullable<decimal> BS_97 { get; set; }
        public Nullable<decimal> BS_98 { get; set; }
        public Nullable<decimal> BS_99 { get; set; }
        public Nullable<decimal> BS_100 { get; set; }
        public Nullable<decimal> BS_101 { get; set; }
        public Nullable<decimal> BS_102 { get; set; }
        public Nullable<decimal> BS_103 { get; set; }
        public Nullable<decimal> BS_104 { get; set; }
        public Nullable<decimal> BS_105 { get; set; }
        public Nullable<decimal> BS_106 { get; set; }
        public Nullable<decimal> BS_107 { get; set; }
        public Nullable<decimal> BS_108 { get; set; }
        public Nullable<decimal> BS_109 { get; set; }
        public Nullable<decimal> BS_110 { get; set; }
        public Nullable<decimal> BS_111 { get; set; }
        public Nullable<decimal> BS_112 { get; set; }
        public Nullable<decimal> BS_113 { get; set; }
        public Nullable<decimal> BS_114 { get; set; }
        public Nullable<decimal> BS_115 { get; set; }
        public Nullable<decimal> BS_116 { get; set; }
        public Nullable<decimal> BS_117 { get; set; }
        public Nullable<decimal> BS_118 { get; set; }
        public Nullable<decimal> BS_119 { get; set; }
        public Nullable<decimal> BS_120 { get; set; }
    }
}
