//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOND_FIN_CASH_TACB
    {
        public long ID { get; set; }
        public Nullable<short> ISVALID { get; set; }
        public Nullable<System.DateTime> CCXEID { get; set; }
        public Nullable<long> COM_UNI_CODE { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<short> SHEET_MARK_PAR { get; set; }
        public Nullable<short> SHEET_ATTR_PAR { get; set; }
        public Nullable<decimal> CF_01 { get; set; }
        public Nullable<decimal> CF_02 { get; set; }
        public Nullable<decimal> CF_03 { get; set; }
        public Nullable<decimal> CF_04 { get; set; }
        public Nullable<decimal> CF_05 { get; set; }
        public Nullable<decimal> CF_06 { get; set; }
        public Nullable<decimal> CF_07 { get; set; }
        public Nullable<decimal> CF_08 { get; set; }
        public Nullable<decimal> CF_09 { get; set; }
        public Nullable<decimal> CF_10 { get; set; }
        public Nullable<decimal> CF_11 { get; set; }
        public Nullable<decimal> CF_12 { get; set; }
        public Nullable<decimal> CF_13 { get; set; }
        public Nullable<decimal> CF_14 { get; set; }
        public Nullable<decimal> CF_15 { get; set; }
        public Nullable<decimal> CF_16 { get; set; }
        public Nullable<decimal> CF_17 { get; set; }
        public Nullable<decimal> CF_18 { get; set; }
        public Nullable<decimal> CF_19 { get; set; }
        public Nullable<decimal> CF_20 { get; set; }
        public Nullable<decimal> CF_21 { get; set; }
        public Nullable<decimal> CF_22 { get; set; }
        public Nullable<decimal> CF_23 { get; set; }
        public Nullable<decimal> CF_24 { get; set; }
        public Nullable<decimal> CF_25 { get; set; }
        public Nullable<decimal> CF_26 { get; set; }
        public Nullable<decimal> CF_27 { get; set; }
        public Nullable<decimal> CF_28 { get; set; }
        public Nullable<decimal> CF_29 { get; set; }
        public Nullable<decimal> CF_30 { get; set; }
        public Nullable<decimal> CF_31 { get; set; }
        public Nullable<decimal> CF_32 { get; set; }
        public Nullable<decimal> CF_33 { get; set; }
        public Nullable<decimal> CF_34 { get; set; }
        public Nullable<decimal> CF_35 { get; set; }
        public Nullable<decimal> CF_36 { get; set; }
        public Nullable<decimal> CF_37 { get; set; }
        public Nullable<decimal> CF_38 { get; set; }
        public Nullable<decimal> CF_39 { get; set; }
        public Nullable<decimal> CF_40 { get; set; }
        public Nullable<decimal> CF_41 { get; set; }
        public Nullable<decimal> CF_42 { get; set; }
        public Nullable<decimal> CF_4201 { get; set; }
        public Nullable<decimal> CF_43 { get; set; }
        public Nullable<decimal> CF_44 { get; set; }
        public Nullable<decimal> CF_45 { get; set; }
        public Nullable<decimal> CF_46 { get; set; }
        public Nullable<decimal> CF_47 { get; set; }
        public Nullable<decimal> CF_48 { get; set; }
        public Nullable<decimal> CF_49 { get; set; }
        public Nullable<decimal> CF_4901 { get; set; }
        public Nullable<decimal> CF_50 { get; set; }
        public Nullable<decimal> CF_51 { get; set; }
        public Nullable<decimal> CF_52 { get; set; }
        public Nullable<decimal> CF_53 { get; set; }
        public Nullable<decimal> CF_54 { get; set; }
        public Nullable<decimal> CF_55 { get; set; }
        public Nullable<decimal> CF_56 { get; set; }
        public Nullable<decimal> CF_57 { get; set; }
        public Nullable<decimal> CF_58 { get; set; }
        public Nullable<decimal> CF_59 { get; set; }
        public Nullable<decimal> CF_60 { get; set; }
        public Nullable<decimal> CF_61 { get; set; }
        public Nullable<decimal> CF_62 { get; set; }
        public Nullable<decimal> CF_63 { get; set; }
        public Nullable<decimal> CF_64 { get; set; }
        public Nullable<decimal> CF_65 { get; set; }
        public Nullable<decimal> CF_66 { get; set; }
        public Nullable<decimal> CF_67 { get; set; }
        public Nullable<decimal> CF_68 { get; set; }
        public Nullable<decimal> CF_69 { get; set; }
        public Nullable<decimal> CF_70 { get; set; }
        public Nullable<decimal> CF_71 { get; set; }
        public Nullable<decimal> CF_72 { get; set; }
        public Nullable<decimal> CF_73 { get; set; }
        public Nullable<decimal> CF_74 { get; set; }
        public Nullable<decimal> CF_75 { get; set; }
        public Nullable<decimal> CF_76 { get; set; }
        public Nullable<decimal> CF_77 { get; set; }
        public Nullable<decimal> CF_78 { get; set; }
        public Nullable<decimal> CF_79 { get; set; }
        public Nullable<decimal> CF_80 { get; set; }
        public Nullable<decimal> CF_81 { get; set; }
        public Nullable<decimal> CF_82 { get; set; }
        public Nullable<decimal> CF_83 { get; set; }
        public Nullable<decimal> CF_84 { get; set; }
        public Nullable<decimal> CF_85 { get; set; }
        public Nullable<decimal> CF_86 { get; set; }
    }
}
