//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BONDFUTURECONTRACT
    {
        public string NAME { get; set; }
        public Nullable<System.DateTime> MATURITY_DT { get; set; }
        public Nullable<System.DateTime> SETTLE_ST { get; set; }
        public Nullable<System.DateTime> SETTLE_ED { get; set; }
        public Nullable<decimal> ISVALID { get; set; }
        public Nullable<System.DateTime> LASTUPDATE { get; set; }
    }
}
