//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOND_FIN_PROF_TAPB
    {
        public long ID { get; set; }
        public Nullable<short> ISVALID { get; set; }
        public Nullable<System.DateTime> CCXEID { get; set; }
        public Nullable<long> COM_UNI_CODE { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<short> SHEET_MARK_PAR { get; set; }
        public Nullable<short> SHEET_ATTR_PAR { get; set; }
        public Nullable<decimal> PF_01 { get; set; }
        public Nullable<decimal> PF_02 { get; set; }
        public Nullable<decimal> PF_03 { get; set; }
        public Nullable<decimal> PF_0301 { get; set; }
        public Nullable<decimal> PF_0302 { get; set; }
        public Nullable<decimal> PF_04 { get; set; }
        public Nullable<decimal> PF_0401 { get; set; }
        public Nullable<decimal> PF_0402 { get; set; }
        public Nullable<decimal> PF_0403 { get; set; }
        public Nullable<decimal> PF_0404 { get; set; }
        public Nullable<decimal> PF_0405 { get; set; }
        public Nullable<decimal> PF_05 { get; set; }
        public Nullable<decimal> PF_06 { get; set; }
        public Nullable<decimal> PF_0601 { get; set; }
        public Nullable<decimal> PF_07 { get; set; }
        public Nullable<decimal> PF_08 { get; set; }
        public Nullable<decimal> PF_09 { get; set; }
        public Nullable<decimal> PF_10 { get; set; }
        public Nullable<decimal> PF_11 { get; set; }
        public Nullable<decimal> PF_12 { get; set; }
        public Nullable<decimal> PF_13 { get; set; }
        public Nullable<decimal> PF_14 { get; set; }
        public Nullable<decimal> PF_15 { get; set; }
        public Nullable<decimal> PF_16 { get; set; }
        public Nullable<decimal> PF_17 { get; set; }
        public Nullable<decimal> PF_18 { get; set; }
        public Nullable<decimal> PF_19 { get; set; }
        public Nullable<decimal> PF_20 { get; set; }
        public Nullable<decimal> PF_21 { get; set; }
        public Nullable<decimal> PF_22 { get; set; }
        public Nullable<decimal> PF_23 { get; set; }
        public Nullable<decimal> PF_24 { get; set; }
        public Nullable<decimal> PF_25 { get; set; }
        public Nullable<decimal> PF_26 { get; set; }
        public Nullable<decimal> PF_27 { get; set; }
        public Nullable<decimal> PF_28 { get; set; }
        public Nullable<decimal> PF_29 { get; set; }
        public Nullable<decimal> PF_30 { get; set; }
        public Nullable<decimal> PF_31 { get; set; }
        public Nullable<decimal> PF_3101 { get; set; }
        public Nullable<decimal> PF_32 { get; set; }
        public Nullable<decimal> PF_33 { get; set; }
        public Nullable<decimal> PF_34 { get; set; }
        public Nullable<decimal> PF_35 { get; set; }
        public Nullable<decimal> PF_3501 { get; set; }
        public Nullable<decimal> PF_36 { get; set; }
        public Nullable<decimal> PF_37 { get; set; }
        public Nullable<decimal> PF_38 { get; set; }
        public Nullable<decimal> PF_39 { get; set; }
        public Nullable<decimal> PF_40 { get; set; }
        public Nullable<decimal> PF_41 { get; set; }
        public Nullable<decimal> PF_42 { get; set; }
        public Nullable<decimal> PF_43 { get; set; }
        public Nullable<decimal> PF_44 { get; set; }
        public Nullable<decimal> PF_45 { get; set; }
        public Nullable<decimal> PF_46 { get; set; }
        public Nullable<decimal> PF_47 { get; set; }
    }
}
