//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOND_ISS_INFO
    {
        public long ID { get; set; }
        public Nullable<short> ISVALID { get; set; }
        public Nullable<System.DateTime> CCXEID { get; set; }
        public Nullable<long> BOND_ID { get; set; }
        public string OPT_DES { get; set; }
        public Nullable<System.DateTime> ISS_DECL_DATE { get; set; }
        public string ISS_OBJ { get; set; }
        public string ISS_CLS { get; set; }
        public Nullable<decimal> ISS_FEE_RATE { get; set; }
        public Nullable<System.DateTime> ISS_START_DATE { get; set; }
        public Nullable<System.DateTime> ISS_END_DATE { get; set; }
        public Nullable<decimal> PLAN_ISS_AMUT { get; set; }
        public string COLL_CAP_PURP { get; set; }
        public Nullable<System.DateTime> PAY_START_DATE { get; set; }
        public Nullable<System.DateTime> PAY_END_DATE { get; set; }
        public Nullable<decimal> SUBS_UNIT { get; set; }
        public Nullable<decimal> LEAST_SUBS_UNIT { get; set; }
        public string DISTRI_OBJ { get; set; }
        public Nullable<short> UNDE_CLS_PAR { get; set; }
        public Nullable<System.DateTime> BOKEP_DATE { get; set; }
        public Nullable<decimal> ACTU_ISS_AMUT { get; set; }
        public Nullable<decimal> ACTU_FIR_ISS_AMUT { get; set; }
        public Nullable<decimal> ISS_PRI { get; set; }
        public Nullable<decimal> BOND_PAR_VAL { get; set; }
        public Nullable<System.DateTime> BID_DATE { get; set; }
        public Nullable<System.DateTime> DEBT_REG_DATE { get; set; }
        public Nullable<short> BOND_ISS_YEAR { get; set; }
        public Nullable<short> IS_REPU_PAR { get; set; }
        public Nullable<short> IS_REDEM_PAR { get; set; }
        public Nullable<short> IS_RESA_PAR { get; set; }
        public Nullable<short> IS_HEDGE_PAR { get; set; }
        public Nullable<short> IS_TAX_FREE_PAR { get; set; }
        public Nullable<short> IS_GUAR_PAR { get; set; }
        public Nullable<short> CURY_CLS_PAR { get; set; }
    }
}
