//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BondDBEntities : DbContext
    {
        public BondDBEntities()
            : base("name=BondDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<GCODES_CDC_ASSET_CLASS_CDS> GCODES_CDC_ASSET_CLASS_CDS { get; set; }
        public DbSet<GCODES_COUPON_CLASS_CDS> GCODES_COUPON_CLASS_CDS { get; set; }
        public DbSet<GCODES_SECOFF_CDS> GCODES_SECOFF_CDS { get; set; }
        public DbSet<GOVCORP_ASSET_IDENT> GOVCORP_ASSET_IDENT { get; set; }
        public DbSet<V_BOND_CN> V_BOND_CN { get; set; }
        public DbSet<V_BOND_EN> V_BOND_EN { get; set; }
        public DbSet<V_ASSET> V_ASSET { get; set; }
        public DbSet<BONDFUTURECONTRACT> BONDFUTURECONTRACT { get; set; }
        public DbSet<BOND> BOND { get; set; }
        public DbSet<TYPELIST> TYPELIST { get; set; }
        public DbSet<TYPEORDER> TYPEORDER { get; set; }
    }
}
