//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOND_SIZE_CHAN
    {
        public long ID { get; set; }
        public Nullable<short> ISVALID { get; set; }
        public Nullable<System.DateTime> CCXEID { get; set; }
        public Nullable<long> BOND_ID { get; set; }
        public Nullable<System.DateTime> DECL_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<decimal> TOTAL_SIZE { get; set; }
        public Nullable<decimal> EXCHANGE_IB_SIZE { get; set; }
        public Nullable<decimal> EXCHANGE_SIZE { get; set; }
        public Nullable<decimal> SH_SIZE { get; set; }
        public Nullable<decimal> SZ_SIZE { get; set; }
        public Nullable<decimal> IB_SIZE { get; set; }
        public Nullable<decimal> OTC_SIZE { get; set; }
        public Nullable<decimal> OTHER_SIZE { get; set; }
        public Nullable<decimal> SIZE_CHAN { get; set; }
        public Nullable<short> CHAN_TYPE_PAR { get; set; }
    }
}
