//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUSINESSTYPEINFO
    {
        public BUSINESSTYPEINFO()
        {
            this.FILETYPEINFOes = new HashSet<FILETYPEINFO>();
            this.FILEDETAILs = new HashSet<FILEDETAIL>();
        }
    
        public decimal ID_C { get; set; }
        public string CODE { get; set; }
        public string BUSINESSTYPENAMECN { get; set; }
        public string BUSINESSTYPENAMEEN { get; set; }
        public string COMMENT_C { get; set; }
        public Nullable<System.DateTime> CTIME { get; set; }
        public Nullable<System.DateTime> MTIME { get; set; }
        public decimal ISVALID { get; set; }
    
        public virtual ICollection<FILETYPEINFO> FILETYPEINFOes { get; set; }
        public virtual ICollection<FILEDETAIL> FILEDETAILs { get; set; }
    }
}
