//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFP_PROFITSHEET
    {
        public long SEQ { get; set; }
        public System.DateTime CTIME { get; set; }
        public System.DateTime MTIME { get; set; }
        public short ISVALID { get; set; }
        public long INNER_CODE { get; set; }
        public System.DateTime DECLAREDATE { get; set; }
        public long PJT_CLS { get; set; }
        public long DIV_CLS { get; set; }
        public long TIMES { get; set; }
        public Nullable<decimal> DIST_INCM { get; set; }
        public Nullable<decimal> DIV_UPPER { get; set; }
        public Nullable<decimal> DIV_LOWER { get; set; }
        public Nullable<decimal> FINAL_DIV { get; set; }
        public Nullable<System.DateTime> INCM_DIST_DATE { get; set; }
        public Nullable<System.DateTime> REGI_DATE { get; set; }
        public Nullable<System.DateTime> EX_DATE { get; set; }
        public Nullable<System.DateTime> PROVIDE_DATE { get; set; }
        public Nullable<System.DateTime> ACC_DATE { get; set; }
        public Nullable<System.DateTime> RE_INVST_DATE { get; set; }
        public Nullable<System.DateTime> RE_INVST_ACC_DATE { get; set; }
        public Nullable<System.DateTime> RE_INVST_QRY_START_DATE { get; set; }
        public string TARGET { get; set; }
        public decimal GENIUS_UID { get; set; }
    }
}
