//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFP_FEE_CHNG
    {
        public long SEQ { get; set; }
        public System.DateTime CTIME { get; set; }
        public System.DateTime MTIME { get; set; }
        public short ISVALID { get; set; }
        public long INNER_CODE { get; set; }
        public Nullable<System.DateTime> DECLAREDATE { get; set; }
        public long FEE_TYPE { get; set; }
        public System.DateTime STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public long SRL_NO { get; set; }
        public Nullable<long> FEE_UNIT { get; set; }
        public Nullable<decimal> FEE_LOWER_LMT { get; set; }
        public Nullable<long> FEE_RLTN { get; set; }
        public Nullable<decimal> FEE_UPPER_LMT { get; set; }
        public string MNY_UNIT { get; set; }
        public Nullable<decimal> MNY_LOWER_LMT { get; set; }
        public Nullable<long> MNY_RLTN { get; set; }
        public Nullable<decimal> MNY_UPPER_LMT { get; set; }
        public Nullable<long> TERM_UNIT { get; set; }
        public Nullable<decimal> TERM_LOWER_LMT { get; set; }
        public Nullable<long> TERM_RLTN { get; set; }
        public Nullable<decimal> TERM_UPPER_LMT { get; set; }
        public Nullable<decimal> ANNU_YLD_LOW_LIM { get; set; }
        public Nullable<long> ANNU_YLD_RLTN { get; set; }
        public Nullable<decimal> ANNU_YLD_UP_LIM { get; set; }
        public decimal GENIUS_UID { get; set; }
        public Nullable<decimal> UNT_NV_UP { get; set; }
        public Nullable<decimal> UNT_NV_LOW { get; set; }
        public Nullable<long> UNT_NV_RLTN { get; set; }
        public string REMARK { get; set; }
        public string FEE_STD { get; set; }
        public Nullable<decimal> FEE_EXER { get; set; }
        public string FEE_EXER_TYPE { get; set; }
        public string FEE_EXER_TERM { get; set; }
        public Nullable<long> FEE_BENMRK { get; set; }
    }
}
