//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMAEntities : DbContext
    {
        public CMAEntities()
            : base("name=CMAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<MENU> MENUs { get; set; }
        public DbSet<MENUNODEACTION> MENUNODEACTIONs { get; set; }
        public DbSet<MENUNODELAYOUT> MENUNODELAYOUTs { get; set; }
        public DbSet<REPORTCOLUMNDEFINITION> REPORTCOLUMNDEFINITIONs { get; set; }
        public DbSet<REPORTDEFINITION> REPORTDEFINITIONs { get; set; }
        public DbSet<REPORTEXTRAHEADERDEFINITION> REPORTEXTRAHEADERDEFINITIONs { get; set; }
        public DbSet<COLUMNDEFINITION> COLUMNDEFINITIONs { get; set; }
        public DbSet<ITEMDEFINITION> ITEMDEFINITIONs { get; set; }
        public DbSet<HOMEANNOUNCEMENT> HOMEANNOUNCEMENTs { get; set; }
        public DbSet<COALCHARTLEGEND> COALCHARTLEGENDs { get; set; }
        public DbSet<COALFILTER> COALFILTERs { get; set; }
        public DbSet<HOMEFILE> HOMEFILEs { get; set; }
        public DbSet<HOMEITEM> HOMEITEMs { get; set; }
        public DbSet<HOMEMODULE> HOMEMODULEs { get; set; }
        public DbSet<USERCOLUMNSETTING> USERCOLUMNSETTINGS { get; set; }
        public DbSet<LOCALIZATION> LOCALIZATIONs { get; set; }
    }
}
