//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class COALCHARTLEGEND
    {
        public decimal REPORTID { get; set; }
        public string CHARTSQL { get; set; }
        public string UNIT { get; set; }
        public string LEGEND { get; set; }
        public string CHARTYLABEL_CN { get; set; }
        public string CHARTYLABEL_EN { get; set; }
        public string CHARTTITLE_CN { get; set; }
        public string CHARTTITLE_EN { get; set; }
    }
}
