//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class COALFILTER
    {
        public decimal ID { get; set; }
        public Nullable<decimal> REPORTID { get; set; }
        public string FILERSQL { get; set; }
        public Nullable<decimal> ISPRIMARY { get; set; }
        public string DEFAULTARG { get; set; }
        public string NAME_CN { get; set; }
        public string NAME_EN { get; set; }
        public string FIELDNAME { get; set; }
        public string FILERSQL_EN { get; set; }
    }
}
