//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISC_ACCE_CFP
    {
        public long SEQ { get; set; }
        public System.DateTime CTIME { get; set; }
        public System.DateTime MTIME { get; set; }
        public short ISVALID { get; set; }
        public string DISC_ID { get; set; }
        public long ACCE_ORDER { get; set; }
        public string ACCE_ROUTE { get; set; }
        public string ACCE_TYPE { get; set; }
        public string ACCE_TITLE { get; set; }
        public decimal GENIUS_UID { get; set; }
        public string ACCE_ROUTE_MD5 { get; set; }
    }
}
