//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILEINFO
    {
        public Nullable<decimal> ID { get; set; }
        public string TITLECN { get; set; }
        public string TITLEEN { get; set; }
        public Nullable<int> TOPICID { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string SUBMITTERID { get; set; }
        public System.DateTime SUBMITDATE { get; set; }
        public string APPROVER { get; set; }
        public Nullable<System.DateTime> APPROVEDATE { get; set; }
        public string FILETYPE { get; set; }
        public string RIC { get; set; }
        public Nullable<decimal> HITS { get; set; }
        public Nullable<decimal> RATING { get; set; }
        public string DESCRCN { get; set; }
        public string DESCREN { get; set; }
        public string AUTHORRM { get; set; }
        public string AUTHOREMAIL { get; set; }
        public string AUTHOR { get; set; }
        public string TAG { get; set; }
        public string UPLOADTYPE { get; set; }
        public string SOURCE { get; set; }
        public Nullable<System.DateTime> REPORTDATE { get; set; }
        public Nullable<short> ISCOMMUNICATABLE { get; set; }
        public string FILENAME { get; set; }
        public Nullable<int> SYNCID { get; set; }
        public Nullable<System.DateTime> LASTCHANGEDATE { get; set; }
        public string SYNCTOPICCODE { get; set; }
        public Nullable<int> SYNCMODULEID { get; set; }
        public Nullable<int> DISPLAYORDER { get; set; }
    }
}
