//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIN_PRD_RPT
    {
        public long SEQ { get; set; }
        public System.DateTime CTIME { get; set; }
        public System.DateTime MTIME { get; set; }
        public short ISVALID { get; set; }
        public decimal GENIUS_UID { get; set; }
        public long RPT_ID { get; set; }
        public string RPT_TITLE { get; set; }
        public Nullable<long> RPT_TYPE { get; set; }
        public Nullable<System.DateTime> WRITEDATE { get; set; }
        public string RPT_SRC { get; set; }
        public string ACCE_ROUTE { get; set; }
        public Nullable<long> FIN_PRD_TYPE { get; set; }
    }
}
