//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNDAMENTALFIELDMAPPING
    {
        public decimal ID { get; set; }
        public string FIELD_NAME { get; set; }
        public string FUNDAMENATAL_TYPE { get; set; }
        public string MAPPING_NAME { get; set; }
        public string ENGLISH_NAME { get; set; }
        public string CHINESE_NAME { get; set; }
        public Nullable<decimal> FIELD_INDEX { get; set; }
        public Nullable<decimal> PARENT_ID { get; set; }
        public Nullable<decimal> IS_PARENT { get; set; }
        public Nullable<decimal> INDENT_LEVEL { get; set; }
    }
}
