//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCODES_COUPON_CLASS_CDS
    {
        public string COUPON_CLASS_CD { get; set; }
        public string COUPON_CLASS_SDESCR { get; set; }
        public string COUPON_CLASS_DESCR { get; set; }
        public Nullable<System.DateTime> ASSET_LAST_CHG_DT { get; set; }
    }
}
