//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCODES_SECOFF_CDS
    {
        public int SECOFF_CD { get; set; }
        public string SECOFF_DESCR { get; set; }
        public string AUCTION_FL { get; set; }
        public string PRIVATE_PLACE_FL { get; set; }
        public string RULE_144A_FL { get; set; }
        public Nullable<System.DateTime> ASSET_LAST_CHG_DT { get; set; }
    }
}
