//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_REF
    {
        public long SEQ { get; set; }
        public System.DateTime CTIME { get; set; }
        public System.DateTime MTIME { get; set; }
        public short ISVALID { get; set; }
        public long CLS_CODE { get; set; }
        public string CLS_NAME { get; set; }
        public string REF_CODE { get; set; }
        public string REF_NAME { get; set; }
        public string REF_MEANING { get; set; }
        public decimal GENIUS_UID { get; set; }
    }
}
