//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GETNEWINSTITUTION
    {
        public string NAMECN { get; set; }
        public string NAMEEN { get; set; }
        public Nullable<decimal> MODULEID { get; set; }
        public string CREATER { get; set; }
        public Nullable<decimal> ISAPPROVE { get; set; }
        public Nullable<decimal> ISINTERNALAPPROVE { get; set; }
        public Nullable<decimal> ISDIRECTDELETE { get; set; }
        public Nullable<decimal> HITS { get; set; }
        public string RMLINK { get; set; }
        public string TAG { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string SYNCCODE { get; set; }
        public Nullable<System.DateTime> LASTCHANGEDATE { get; set; }
        public Nullable<decimal> INSTITUTIONORDER { get; set; }
    }
}
