//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GETNEWFILE
    {
        public string TITLECN { get; set; }
        public string TITLEEN { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public string SUBMITERNAME { get; set; }
        public string SUBMITER { get; set; }
        public string SUBMITERRM { get; set; }
        public Nullable<System.DateTime> SUBMITDATE { get; set; }
        public string APPROVER { get; set; }
        public string FILETYPE { get; set; }
        public string RIC { get; set; }
        public Nullable<decimal> HITS { get; set; }
        public string AUTHOR { get; set; }
        public string TAG { get; set; }
        public string UPLOADTYPE { get; set; }
        public string SOURCES { get; set; }
        public Nullable<System.DateTime> REPORTDATE { get; set; }
        public Nullable<decimal> ISCOMMUNICATABLE { get; set; }
        public decimal SYNCID { get; set; }
        public string SYNCTOPICCODE { get; set; }
        public Nullable<decimal> SYNCMODULEID { get; set; }
        public Nullable<System.DateTime> LASTCHANGEDATE { get; set; }
    }
}
