//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GETRESEACHREPORTBYTYPE
    {
        public Nullable<decimal> NUM { get; set; }
        public string CODE { get; set; }
        public string INSTITUTIONNAMECN { get; set; }
        public string INSTITUTIONNAMEEN { get; set; }
        public Nullable<System.DateTime> MTIME { get; set; }
        public string INSTITUTIONEXTENSION { get; set; }
        public Nullable<decimal> INSTITUTIONORDER { get; set; }
        public string FILETYPENAMECN { get; set; }
        public string FILETYPENAMEEN { get; set; }
        public string BUSINESSCODETYPE { get; set; }
        public Nullable<decimal> TYPEORDER { get; set; }
        public Nullable<System.DateTime> FILETYPECTIME { get; set; }
        public string FILETYPECODE { get; set; }
        public string FILENAMECN { get; set; }
        public string FILENAMEEN { get; set; }
        public decimal FILEID { get; set; }
        public string EXTENSION { get; set; }
        public Nullable<System.DateTime> REPORTDATE { get; set; }
    }
}
