//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOVCORP_ASSET_IDENT
    {
        public string ASSETID { get; set; }
        public string ID_CD { get; set; }
        public System.DateTime ID_EFF_DT { get; set; }
        public string ID_NUMBER { get; set; }
        public string ISS_TYPE_CD { get; set; }
        public string ID_TYPE { get; set; }
        public Nullable<System.DateTime> ASSET_LAST_CHG_DT { get; set; }
    }
}
