//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOMEMODULE
    {
        public HOMEMODULE()
        {
            this.HOMEITEMs = new HashSet<HOMEITEM>();
        }
    
        public decimal ID { get; set; }
        public string NAMECN { get; set; }
        public string NAMEEN { get; set; }
        public Nullable<decimal> ISMAIN { get; set; }
        public Nullable<decimal> ISVALID { get; set; }
        public Nullable<decimal> DISPLAYORDER { get; set; }
    
        public virtual ICollection<HOMEITEM> HOMEITEMs { get; set; }
    }
}
