//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOMEANNOUNCEMENT
    {
        public decimal ID { get; set; }
        public string CONTENTEN { get; set; }
        public string CONTENTCN { get; set; }
        public Nullable<decimal> ISVALID { get; set; }
    }
}
