//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IPPEntities : DbContext
    {
        public IPPEntities()
            : base("name=IPPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FILEINFO> FILEINFOs { get; set; }
        public DbSet<MODULEINFO> MODULEINFOs { get; set; }
        public DbSet<TOPICAPPROVER> TOPICAPPROVERs { get; set; }
        public DbSet<TOPIC> TOPICs { get; set; }
        public DbSet<SUBMITTER> SUBMITTERs { get; set; }
    }
}
