//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMDEFINITION
    {
        public decimal ID { get; set; }
        public Nullable<decimal> REPORTID { get; set; }
        public Nullable<decimal> ITEMID { get; set; }
        public string VIEWMODELNAME1 { get; set; }
        public string VIEWMODELNAME2 { get; set; }
        public string VIEWNAME1 { get; set; }
        public string VIEWNAME2 { get; set; }
        public string TABLENAME1 { get; set; }
        public string TABLEFILTER1 { get; set; }
        public string TABLENAME2 { get; set; }
        public string TABLEFILTER2 { get; set; }
        public string TABNAME_CN { get; set; }
        public string TABNAME_EN { get; set; }
        public string CHARTSP1 { get; set; }
        public string CHARTSP2 { get; set; }
        public Nullable<decimal> TABORDER { get; set; }
        public Nullable<short> ISVALID { get; set; }
        public string LEGEND { get; set; }
    }
}
