//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCALIZATION
    {
        public string TABLE_NAME { get; set; }
        public string TABLE_CD { get; set; }
        public string ENGLISH_NAME { get; set; }
        public string CHINESE_NAME { get; set; }
        public string MEMO { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
        public Nullable<decimal> ROW_LEVEL { get; set; }
        public string CHART_SOURCE { get; set; }
    }
}
