//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public decimal ID { get; set; }
        public decimal PARENT_ID { get; set; }
        public Nullable<decimal> IS_REPORT { get; set; }
        public string ENGLISH_NAME { get; set; }
        public string CHINESE_NAME { get; set; }
        public string CHINESE_NAME_TW { get; set; }
        public string RIC { get; set; }
        public Nullable<decimal> GROUP_TYPE { get; set; }
        public Nullable<decimal> REPORT_ID { get; set; }
        public Nullable<decimal> NODEORDER { get; set; }
        public Nullable<decimal> ACTIONTYPE { get; set; }
        public Nullable<decimal> ISVISIBLE { get; set; }
        public Nullable<decimal> ISTREEVISIBLE { get; set; }
    }
}
