//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OpenMarketEntities : DbContext
    {
        public OpenMarketEntities()
            : base("name=OpenMarketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EJVASSET> EJVASSETs { get; set; }
        public DbSet<OPENMARKETOPERATION> OPENMARKETOPERATIONs { get; set; }
        public DbSet<V_OPENMARKET> V_OPENMARKET { get; set; }
        public DbSet<V_OPENMARKET_SEARCH> V_OPENMARKET_SEARCH { get; set; }
    }
}
