//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPENMARKETOPERATION
    {
        public string RIC { get; set; }
        public string SHORTNAME { get; set; }
        public System.DateTime ISSUEDATE { get; set; }
        public Nullable<System.DateTime> MATDATE { get; set; }
        public Nullable<decimal> ISSUERATE { get; set; }
        public Nullable<decimal> ISSUEVOLUME { get; set; }
        public Nullable<decimal> ISSUEYIELD { get; set; }
        public Nullable<decimal> TUENOVERVOLUME { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> MODIFYDATE { get; set; }
        public Nullable<decimal> PRODPERMISSION { get; set; }
    }
}
