//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORG_PROFILE
    {
        public Nullable<int> SEQ { get; set; }
        public Nullable<System.DateTime> CTIME { get; set; }
        public Nullable<System.DateTime> MTIME { get; set; }
        public Nullable<short> ISVALID { get; set; }
        public string REMARK { get; set; }
        public int ORGCODE { get; set; }
        public Nullable<System.DateTime> DECLAREDATE { get; set; }
        public string CNAME { get; set; }
        public string CSNAME { get; set; }
        public string CSPELL { get; set; }
        public string ENAME { get; set; }
        public string ESNAME { get; set; }
        public Nullable<decimal> REGI_CAP { get; set; }
        public Nullable<int> CURNCY { get; set; }
        public string REGI_ADDR { get; set; }
        public string OFFICE_ADDR { get; set; }
        public string WEB_SITE { get; set; }
        public string POSTCODE { get; set; }
        public string LEG_PERSON { get; set; }
        public string GEN_MANAGER { get; set; }
        public string DISTRICT_NO { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string CONTACT_PERSON { get; set; }
        public string BOARD_SECTRY { get; set; }
        public string SECTRY_TEL { get; set; }
        public string SECTRY_FAX { get; set; }
        public string CONTACT_ADDR { get; set; }
        public string SECTRY_EMAIL { get; set; }
        public string REPR { get; set; }
        public string REPR_TEL { get; set; }
        public string REPR_FAX { get; set; }
        public string REPR_ADDR { get; set; }
        public string REPR_EMAIL { get; set; }
        public string BRIEF_INTRO { get; set; }
        public string PRI_BIZ { get; set; }
        public string NON_PRI_BIZ { get; set; }
        public Nullable<int> STAFF_NUM { get; set; }
        public Nullable<int> MSTAFF_NUM { get; set; }
        public Nullable<int> TSTAFF_NUM { get; set; }
        public string DISCL_PAPER { get; set; }
        public string DISCL_WEBSITE { get; set; }
        public Nullable<System.DateTime> BUILD_DATE { get; set; }
        public Nullable<System.DateTime> CLOSE_DATE { get; set; }
        public string CLOSE_REASON { get; set; }
        public Nullable<int> ORG_STATUS { get; set; }
        public string REGI_NO { get; set; }
        public string NTAX_NO { get; set; }
        public string LTAX_NO { get; set; }
        public string LISTED { get; set; }
        public string ISSUE_BOND { get; set; }
        public string NATION { get; set; }
        public string REGION { get; set; }
        public string ORG_TYPE { get; set; }
        public string ORG_MTYPE { get; set; }
        public string ORG_STYPE { get; set; }
        public Nullable<int> ORG_FORM { get; set; }
        public string FORM_NAME { get; set; }
        public Nullable<int> MOTHER_CODE { get; set; }
        public Nullable<int> TOPCODE { get; set; }
        public Nullable<int> PARENTCODE { get; set; }
        public string LAYERCODE { get; set; }
        public string STATUS_NAME { get; set; }
        public string CURNCY_NAME { get; set; }
        public string NATION_NAME { get; set; }
        public string REGION_NAME { get; set; }
        public string TYPE_NAME { get; set; }
        public string MTYPE_NAME { get; set; }
        public string STYPE_NAME { get; set; }
        public string MOTHER_NAME { get; set; }
        public string TOP_NAME { get; set; }
        public string PARENT_NAME { get; set; }
        public Nullable<decimal> GENIUS_UID { get; set; }
        public string SERVICE_TEL { get; set; }
        public string PROVINCE { get; set; }
        public string CITY { get; set; }
        public Nullable<int> REGION_CODE { get; set; }
    }
}
