//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUB_AREA_CODE
    {
        public long ID { get; set; }
        public Nullable<short> ISVALID { get; set; }
        public Nullable<System.DateTime> CCXEID { get; set; }
        public Nullable<long> AREA_UNI_CODE { get; set; }
        public Nullable<short> AREA_TYPE_PAR { get; set; }
        public Nullable<short> ADMI_LEVE_PAR { get; set; }
        public string NAT_CODE { get; set; }
        public string ISO_CODE_TWO { get; set; }
        public string ISO_CODE_THR { get; set; }
        public string AREA_CHI_NAME { get; set; }
        public string AREA_CHI_SHORT_NAME { get; set; }
        public string AREA_ENG_NAME { get; set; }
        public string AREA_ENG_SHORT_NAME { get; set; }
        public Nullable<decimal> TIME_DIFF { get; set; }
        public string POST_CODE { get; set; }
        public string AREA_CODE { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<short> IS_VALID { get; set; }
        public Nullable<System.DateTime> DIS_DATE { get; set; }
        public Nullable<long> SUB_UNI_CODE { get; set; }
        public Nullable<long> AREA_UNI_CODE1 { get; set; }
        public string AREA_NAME1 { get; set; }
        public Nullable<long> AREA_UNI_CODE2 { get; set; }
        public string AREA_NAME2 { get; set; }
        public Nullable<long> AREA_UNI_CODE3 { get; set; }
        public string AREA_NAME3 { get; set; }
        public Nullable<long> AREA_UNI_CODE4 { get; set; }
        public string AREA_NAME4 { get; set; }
    }
}
