//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUB_CURY_TYPE
    {
        public long ID { get; set; }
        public Nullable<short> ISVALID { get; set; }
        public Nullable<System.DateTime> CCXEID { get; set; }
        public Nullable<short> CURY_TYPE_PAR { get; set; }
        public string CURY_CHI_NAME { get; set; }
        public string CURY_ENG_NAME { get; set; }
        public string CURY_OLD_SIGN { get; set; }
        public string CURY_STAN_SIGN { get; set; }
        public string CURY_DES { get; set; }
        public string AREA_UNI_CODE { get; set; }
    }
}
