//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUB_ORG_INFO
    {
        public long ID { get; set; }
        public Nullable<short> ISVALID { get; set; }
        public Nullable<System.DateTime> CCXEID { get; set; }
        public Nullable<long> ORG_UNI_CODE { get; set; }
        public string ORG_CHI_NAME { get; set; }
        public string CHI_SHORT_NAME { get; set; }
        public string ORG_ENG_NAME { get; set; }
        public string ENG_SHORT_NAME { get; set; }
        public string CHI_SPE_SHORT_NAME { get; set; }
        public Nullable<decimal> REG_CAP { get; set; }
        public Nullable<short> CURY_TYPE_PAR { get; set; }
        public string REG_ADDR { get; set; }
        public Nullable<long> AREA_UNI_CODE { get; set; }
        public string OFFI_ADDR { get; set; }
        public string POST_CODE { get; set; }
        public string COM_WEB { get; set; }
        public string LEG_PER { get; set; }
        public string GEN_MAN { get; set; }
        public string ORG_CON_PER { get; set; }
        public string ORG_TEL { get; set; }
        public string ORG_FAX { get; set; }
        public string ORG_MAIL_ADDR { get; set; }
        public string ORG_EST_DATE { get; set; }
        public string CUS_CON_TEL { get; set; }
        public Nullable<short> ORG_STA_PAR { get; set; }
        public string IC_REG_CODE { get; set; }
        public string NAT_TAX_REG_CODE { get; set; }
        public string LOC_TAX_REG_CODE { get; set; }
        public Nullable<int> ORG_CLA_BIG_PAR { get; set; }
        public Nullable<int> ORG_CLA_MID_PAR { get; set; }
        public Nullable<int> ORG_CLA_SMA_PAR { get; set; }
        public Nullable<short> ORG_ORGA_FORM_PAR { get; set; }
        public Nullable<long> PARE_COM_CODE { get; set; }
        public Nullable<long> TOP_ORG_CODE { get; set; }
        public Nullable<long> HIGH_LEVEL_ORG_CODE { get; set; }
        public Nullable<long> HIE_CODE { get; set; }
        public string ORG_ABBR { get; set; }
        public string ORG_MAIN_BUSI { get; set; }
        public string ORG_SID_BUSI { get; set; }
        public Nullable<System.DateTime> DIS_DATE { get; set; }
        public string DIS_REAS { get; set; }
        public Nullable<short> ORG_LIST_PAR { get; set; }
        public Nullable<short> IF_ISS_BOND { get; set; }
        public Nullable<short> LIST_MKT { get; set; }
        public string FILE_PATH { get; set; }
    }
}
