//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUB_PAR
    {
        public long ID { get; set; }
        public Nullable<short> ISVALID { get; set; }
        public Nullable<System.DateTime> CCXEID { get; set; }
        public Nullable<long> PAR_SYS_CODE { get; set; }
        public string PAR_SYS_NAME { get; set; }
        public Nullable<long> PAR_CODE { get; set; }
        public string PAR_NAME { get; set; }
        public string PAR_ENG_NAME { get; set; }
        public string PAR_UNIT { get; set; }
    }
}
