//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RATE_ORG_INFO_F
    {
        public long ID { get; set; }
        public Nullable<short> ISVALID { get; set; }
        public Nullable<System.DateTime> CCXEID { get; set; }
        public Nullable<long> COM_UNI_CODE { get; set; }
        public string COM_CHI_NAME { get; set; }
        public string COM_CHI_SHORT_NAME { get; set; }
        public string COM_SPE_SHORT_NAME { get; set; }
        public string COM_ENG_NAME { get; set; }
        public string COM_ENG_SHORT_NAME { get; set; }
        public Nullable<int> TYPE_BIG_PAR { get; set; }
        public Nullable<short> COM_ORGA_FORM_PAR { get; set; }
        public Nullable<long> PARE_COM_CODE { get; set; }
        public string COM_STP { get; set; }
        public string STP_TEL { get; set; }
        public string STP_TAX { get; set; }
        public string STP_CON_ADDR { get; set; }
        public string STP_MAIL { get; set; }
        public string SEC_REPR_NAME { get; set; }
        public string SEC_REPR_TEL { get; set; }
        public string SEC_REPR_TAX { get; set; }
        public string SEC_REPR_CON_ADDR { get; set; }
        public string SEC_REPR_MAIL { get; set; }
        public string INFO_DISC_PER { get; set; }
        public string INFO_DISC_PAP { get; set; }
        public string INFO_DISC_WEB { get; set; }
        public string REG_ADDR { get; set; }
        public Nullable<long> AREA_UNI_CODE { get; set; }
        public string REG_ADDR_POST { get; set; }
        public string OFFI_ADDR { get; set; }
        public string OFFI_ADDR_POST { get; set; }
        public string COM_ADDR { get; set; }
        public string COM_ADDR_POST { get; set; }
        public string COM_WEB { get; set; }
        public string COM_CON_PER { get; set; }
        public string COM_TEL { get; set; }
        public string CUS_CON_TEL { get; set; }
        public string COM_FAX { get; set; }
        public string MAIL_ADDR { get; set; }
        public Nullable<decimal> REG_CAP { get; set; }
        public Nullable<short> CURY_TYPE_PAR { get; set; }
        public string LEG_PER { get; set; }
        public string GEN_MAN { get; set; }
        public string EST_DATE { get; set; }
        public string IC_REG_CODE { get; set; }
        public string NAT_TAX_REG_CODE { get; set; }
        public string LOC_TAX_REG_CODE { get; set; }
        public Nullable<long> TER_ACC_OFFI_CODE { get; set; }
        public string TER_ACC { get; set; }
        public Nullable<long> LAWER_OFFI_CODE { get; set; }
        public string COM_LAWER { get; set; }
        public Nullable<long> CAP_ESTI_ORG_CODE { get; set; }
        public string ESTI_STAFF { get; set; }
        public string MAIN_BUS { get; set; }
        public string SID_BUS { get; set; }
        public string COM_PRO { get; set; }
        public string COM_HIS { get; set; }
        public Nullable<int> STAFF_SUM { get; set; }
        public Nullable<int> STA_PAR { get; set; }
        public Nullable<System.DateTime> DIS_DATE { get; set; }
        public string DIS_REAS { get; set; }
        public Nullable<short> IS_LIST_PAR { get; set; }
        public Nullable<int> TYPE_MID_PAR { get; set; }
    }
}
