//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RATE_REP
    {
        public long ID { get; set; }
        public Nullable<short> ISVALID { get; set; }
        public Nullable<System.DateTime> CCXEID { get; set; }
        public Nullable<long> RATE_ID { get; set; }
        public Nullable<System.DateTime> RATE_WRIT_DATE { get; set; }
        public Nullable<System.DateTime> RATE_PUBL_DATE { get; set; }
        public Nullable<long> ORG_UNI_CODE { get; set; }
        public string RESER_NAME { get; set; }
        public string RATE_TITLE { get; set; }
        public Nullable<short> RATE_TYPE_PAR { get; set; }
        public Nullable<int> RATE_PAG { get; set; }
        public Nullable<long> RATE_FILE_SIZE { get; set; }
        public Nullable<short> RATE_FILE_TYPE_PAR { get; set; }
        public string RATE_FILE_PATH { get; set; }
        public string ATT_PATH_MD5 { get; set; }
    }
}
