//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTEXTRAHEADERDEFINITION
    {
        public decimal REPORT_ID { get; set; }
        public string EXTRA_HEADER_TEXT_CN { get; set; }
        public string EXTRA_HEADER_TEXT_EN { get; set; }
        public decimal EXTRA_HEADER_COLUMN_SPAN { get; set; }
        public decimal EXTRA_HEADER_LEVEL { get; set; }
    }
}
