//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTCOLUMNDEFINITION
    {
        public decimal REPORT_ID { get; set; }
        public string COLUMN_NAME { get; set; }
        public string HEADER_TEXT_EN { get; set; }
        public string HEADER_TEXT_CN { get; set; }
        public string DISPLAY_FORMAT { get; set; }
        public string COLUMN_TYPE { get; set; }
        public Nullable<short> IS_SORTABLE { get; set; }
        public Nullable<decimal> COLUMN_INDEX { get; set; }
        public string COLUMN_STYLE { get; set; }
        public Nullable<short> IS_DETAIL_COLUMN { get; set; }
    }
}
