//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTDEFINITION
    {
        public decimal ID { get; set; }
        public string VIEW_NAME { get; set; }
        public string TABLE_NAME { get; set; }
        public string VIEWMODEL_NAME { get; set; }
        public string COLUMN_LIST { get; set; }
        public string ENGLISH_NAME { get; set; }
        public string CHINESE_NAME { get; set; }
        public string REPORT_TYPE { get; set; }
    }
}
