//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RES_INFO_DATA
    {
        public decimal RES_ID { get; set; }
        public Nullable<System.DateTime> CCXEID { get; set; }
        public string RES_FILE_PATH { get; set; }
        public Nullable<short> ISSYNCED { get; set; }
        public decimal FILEID { get; set; }
    }
}
