//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_CONFIG
    {
        public string ID { get; set; }
        public string TABLETYPE { get; set; }
        public string TABLENAMEEN { get; set; }
        public string TABLENAMECN { get; set; }
        public string FIELDNAMESARRCN { get; set; }
        public string FIELDNAMESARREN { get; set; }
        public string FIELDTYPESARR { get; set; }
        public string KEYFIELDARRS { get; set; }
        public Nullable<int> SPACINGDISTANCE { get; set; }
        public string TABLEENDFLAG { get; set; }
        public string KEYFIELDINDEXARRS { get; set; }
        public string KEYVALUEARRS { get; set; }
    }
}
