//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRUST_PROFILE
    {
        public long SEQ { get; set; }
        public System.DateTime CTIME { get; set; }
        public System.DateTime MTIME { get; set; }
        public short ISVALID { get; set; }
        public decimal GENIUS_UID { get; set; }
        public long INNER_CODE { get; set; }
        public Nullable<System.DateTime> DECLAREDATE { get; set; }
        public string TRUST_NAME { get; set; }
        public string CHI_SPEL { get; set; }
        public string TRUST_SNAME { get; set; }
        public string MAIN_SNAME { get; set; }
        public Nullable<long> MAIN_CODE { get; set; }
        public Nullable<long> ISS_YEAR { get; set; }
        public Nullable<System.DateTime> PROM_STARTDATE { get; set; }
        public Nullable<System.DateTime> PROM_ENDDATE { get; set; }
        public Nullable<long> SALE_DAYS { get; set; }
        public Nullable<long> PERI_TYPE { get; set; }
        public Nullable<decimal> TRUST_PERI { get; set; }
        public string OPEN_REMARK { get; set; }
        public string CLOSE_REMARK { get; set; }
        public Nullable<System.DateTime> BUILD_DATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<System.DateTime> EXPE_ENDDATE { get; set; }
        public Nullable<long> IS_BRG_FRD { get; set; }
        public Nullable<long> IS_DLY { get; set; }
        public Nullable<long> IS_STRU { get; set; }
        public string STRU_RATIO { get; set; }
        public Nullable<long> IS_PE { get; set; }
        public Nullable<long> IS_CURNCY { get; set; }
        public Nullable<long> IS_TOT { get; set; }
        public string TRUST_TYPE { get; set; }
        public string SEC_INVEST_TYPE { get; set; }
        public Nullable<long> INV_FLD { get; set; }
        public string TRUST_MNG { get; set; }
        public Nullable<long> LIQU_REASON { get; set; }
        public Nullable<decimal> EXP_YLD { get; set; }
        public Nullable<long> CURNCY { get; set; }
        public string EXP_YLD_REMARK { get; set; }
        public Nullable<decimal> ACT_YLD { get; set; }
        public Nullable<long> INCOME_TYPE { get; set; }
        public string ACT_YLD_REMARK { get; set; }
        public Nullable<decimal> PLAN_ISS_SIZE { get; set; }
        public Nullable<decimal> ACTU_ISS_SIZE { get; set; }
        public string ORGNAME { get; set; }
        public Nullable<long> ORGCODE { get; set; }
        public Nullable<long> CONTR_SHT { get; set; }
        public Nullable<decimal> BOOK_VAL { get; set; }
        public Nullable<decimal> MIN_CAP { get; set; }
        public string MIN_CAP_REMARK { get; set; }
        public Nullable<decimal> ADD_CAP { get; set; }
        public string ADD_CAP_REMARK { get; set; }
        public string CRED_ENHA_MODE { get; set; }
        public Nullable<long> NET_FREQ { get; set; }
        public Nullable<System.DateTime> NET_STARTDATE { get; set; }
        public Nullable<System.DateTime> NET_ENDDATE { get; set; }
        public string INVEST_REMARK { get; set; }
        public string PRD_REMARK { get; set; }
        public string FEE_REMARK { get; set; }
        public string RIST_WARE { get; set; }
        public Nullable<decimal> ALERT_LINE { get; set; }
        public string ALERT_LINE_REMARK { get; set; }
        public Nullable<decimal> STOP_LINE { get; set; }
        public string STOP_LINE_REMARK { get; set; }
        public Nullable<long> IS_MERGE { get; set; }
        public string REMARK { get; set; }
        public Nullable<long> PRD_STATUS { get; set; }
        public Nullable<long> TRUST_PERI_UNIT { get; set; }
        public Nullable<decimal> FIN_CYC { get; set; }
        public Nullable<long> FIN_CYC_UNIT { get; set; }
        public string REGI_CODE { get; set; }
    }
}
