//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERCOLUMNSETTING
    {
        public string USERID { get; set; }
        public decimal REPORTID { get; set; }
        public string SETTINGNAME { get; set; }
        public string COLUMNLIST { get; set; }
    }
}
