//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ASSET
    {
        public string ASSET_ID { get; set; }
        public string ID_NUMBER { get; set; }
        public Nullable<decimal> AMT_ISS_TOT { get; set; }
        public string ASSET_DUPLICATE_CD { get; set; }
        public string CALL_TERMS_FL { get; set; }
        public string CPN_CLASS_CD { get; set; }
        public string CPN_TYPE_CD { get; set; }
        public string CURRENCY_CD { get; set; }
        public Nullable<int> DAY_COUNT_CD { get; set; }
        public string FLOAT_FORMULA { get; set; }
        public string FLOAT_INDEX { get; set; }
        public Nullable<decimal> FLOAT_OFFSET { get; set; }
        public string GUARANTEE_FL { get; set; }
        public string ISIN_NM { get; set; }
        public string ISSUERID { get; set; }
        public Nullable<System.DateTime> MATURITY_DT { get; set; }
        public Nullable<decimal> ORIG_AMT_ISS { get; set; }
        public Nullable<System.DateTime> ORIG_DATED_DT { get; set; }
        public Nullable<System.DateTime> ORIG_ISS_DT { get; set; }
        public Nullable<int> PAY_FREQ_CD { get; set; }
        public string PUT_TERMS_FL { get; set; }
        public string SECURED_FL { get; set; }
        public string SECONDARY_INSU_FL { get; set; }
        public string SETTLE_BUS_CTR_CD { get; set; }
        public string CDC_ASSET_CLASS_CD { get; set; }
        public string SENIORITY_CD { get; set; }
        public string OFFER_REGISTRANT_NAME { get; set; }
        public Nullable<decimal> ORIG_AVG_LIFE { get; set; }
        public Nullable<decimal> ORIG_ISS_AMT { get; set; }
        public Nullable<decimal> ORIG_ISS_CPN { get; set; }
        public string ORIG_ISS_CURR_CD { get; set; }
        public Nullable<decimal> ORIG_ISS_PX { get; set; }
        public Nullable<decimal> ORIG_ISS_YLD { get; set; }
        public Nullable<System.DateTime> ORIG_ISSUE_DT { get; set; }
        public Nullable<decimal> ORIG_YLD_MATURITY { get; set; }
        public string SENIORITY_TYPE_CD { get; set; }
        public Nullable<int> TERM_TO_MATURITY { get; set; }
        public string ID_CD { get; set; }
    }
}
