//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_BOND_CN
    {
        public string ASSETID { get; set; }
        public string CODE { get; set; }
        public string PYC { get; set; }
        public string RIC { get; set; }
        public string SHORTNAME { get; set; }
        public Nullable<System.DateTime> ISSUEDATE { get; set; }
        public Nullable<decimal> ISSUEAMOUNT { get; set; }
        public Nullable<decimal> INTERESTRATE { get; set; }
        public Nullable<decimal> ISSUEPRICE { get; set; }
        public string ISSUECOUNTRYCD { get; set; }
        public string ISSUECOUNTRY { get; set; }
        public string TERM { get; set; }
        public string BONDTERMCD { get; set; }
        public string BONDTERM { get; set; }
        public Nullable<decimal> ORIGTERM { get; set; }
        public Nullable<decimal> ORIGAVGLIFE { get; set; }
        public Nullable<decimal> BONDTERMNUMBER { get; set; }
        public Nullable<decimal> YIELD { get; set; }
        public string ISINNUM { get; set; }
        public Nullable<int> DAYCOUNTCD { get; set; }
        public string ORIGISSCURRCD { get; set; }
        public string ISFLOAT { get; set; }
        public string BONDCLASSCD { get; set; }
        public string BONDCLASSDESCR { get; set; }
        public string OPTIONC { get; set; }
        public string OPTIONDESCR { get; set; }
        public string COUPONCLASSCD { get; set; }
        public string COUPONCLASSDESCR { get; set; }
        public Nullable<decimal> PAYFREQUENCYCD { get; set; }
        public string PAYFREQUENCY { get; set; }
        public Nullable<System.DateTime> ANNOUCEMENTDATE { get; set; }
        public Nullable<System.DateTime> ORIGDATEDDATE { get; set; }
        public Nullable<System.DateTime> MATURITYDATE { get; set; }
        public Nullable<System.DateTime> LISTINGDATE { get; set; }
        public string FLOATINDEX { get; set; }
        public string FLOATINDEXDESCR { get; set; }
        public Nullable<decimal> FLOATOFFSET { get; set; }
        public string RATINGCD { get; set; }
        public string RATINGSRCCD { get; set; }
        public string RATINGSRCDESCR { get; set; }
        public Nullable<decimal> FIRSTDAYCLOSINGPRICE { get; set; }
        public Nullable<decimal> FIRSTDAYCHANGE { get; set; }
        public Nullable<decimal> FIRSTDAYVOLUME { get; set; }
        public Nullable<decimal> FIRSTDAYTURNOVERRATE { get; set; }
        public string PARTYRATINGCD { get; set; }
        public string PARTYRATINGSRCCD { get; set; }
        public string PARTYRATINGSRCDESCR { get; set; }
        public string ISSUER { get; set; }
        public string BOOKMANAGER { get; set; }
        public string LEADUNDERWRITER { get; set; }
        public string COUNDERWRITER { get; set; }
        public string UNDERWRITERMEMBER { get; set; }
        public Nullable<System.DateTime> PAYDATE { get; set; }
        public string BONDNAME { get; set; }
        public string STATUSONLIQCD { get; set; }
        public string STATUSONLIQDESCR { get; set; }
        public string CODELIST { get; set; }
        public string ISSUERORGID { get; set; }
        public string ISSUERINDUSECTORCD { get; set; }
        public string ISSUERINDUSECTORDESCR { get; set; }
        public string ISSUERINDUSUBSECTORCD { get; set; }
        public string ISSUERINDUSUBSECTORDESCR { get; set; }
        public string GUARANTORNAME { get; set; }
        public string GUARANTORINDUSECTORCD { get; set; }
        public string GUARANTORINDUSECTORDESCR { get; set; }
        public Nullable<System.DateTime> ENDDATEOFISSUE { get; set; }
        public Nullable<int> ISSUETYPECD { get; set; }
        public string ISSUETYPEDESCR { get; set; }
        public string AUCTIONTYPE { get; set; }
        public Nullable<System.DateTime> AUCTIONDATE { get; set; }
        public Nullable<decimal> TOTALAPPLIEDFOR { get; set; }
        public string SENIORITYCD { get; set; }
        public string SENIORITYDESCR { get; set; }
        public string CIBONDFLAG { get; set; }
        public string CIBONDFLAGDESCR { get; set; }
        public string OTHBONDTYPECD { get; set; }
        public string OTHBONDTYPEDESCR { get; set; }
        public string TAPISSUEFLAG { get; set; }
        public string TERMEX { get; set; }
        public string ITERMEX { get; set; }
        public string PROVINCEOFISSUER { get; set; }
        public string GUARANTORRATING { get; set; }
        public string AUCTIONOJECT { get; set; }
        public string GUARANTORITEM { get; set; }
        public string UNDERWRITERTYPE { get; set; }
        public Nullable<decimal> BIDPRICE { get; set; }
        public string BIDREGION { get; set; }
        public Nullable<decimal> MULTIPURCHASE { get; set; }
        public Nullable<decimal> FEERATE { get; set; }
        public Nullable<decimal> ONLINEPOSITION { get; set; }
        public string ONLINECODE { get; set; }
        public string DOMICILE { get; set; }
        public string DEBTTYPECD { get; set; }
        public string DEBTTYPEDESCR { get; set; }
        public string ASSETTYPECD { get; set; }
        public string ASSETTYPEDESCR { get; set; }
        public string PARTYCNTRYINCORPCD { get; set; }
        public string PARTYCNTRYINCORPDESCR { get; set; }
        public string ISSUERDOMICILE { get; set; }
        public string RATINGINFOCD { get; set; }
        public string RATINGINFO { get; set; }
        public string SECCLASSCD { get; set; }
        public Nullable<System.DateTime> LASTCHANGEDATE { get; set; }
        public string BONDRATINGHIST { get; set; }
        public string BONDISSUERRATING { get; set; }
        public Nullable<decimal> AMTISSTOT { get; set; }
        public Nullable<decimal> PROVINCEORDER { get; set; }
        public string EXCHANGECODE { get; set; }
        public string EXCHANGENAME { get; set; }
        public string TRUSTEECODE { get; set; }
        public string TRUSTEENAME { get; set; }
        public Nullable<decimal> LEADUNDERWRITERNUM { get; set; }
    }
}
