//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_OPENMARKET_SEARCH
    {
        public string CODE { get; set; }
        public System.DateTime ISSUEDATE { get; set; }
        public Nullable<decimal> VOLUME { get; set; }
        public Nullable<decimal> PIRCERATE { get; set; }
        public Nullable<decimal> REFRATE { get; set; }
        public Nullable<System.DateTime> MATURITYDATE { get; set; }
        public string TRADETYPE { get; set; }
        public Nullable<decimal> TERM { get; set; }
        public string ASSETID { get; set; }
        public string TERMEN { get; set; }
        public string TERMCN { get; set; }
        public string CATEGORYTYPE { get; set; }
    }
}
