//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_WMP_AREA_DIC
    {
        public long ID_C { get; set; }
        public Nullable<int> ISS_AREA_CODE { get; set; }
        public string PROV_NAME { get; set; }
        public string ISS_AREA { get; set; }
        public long INNER_CODE { get; set; }
    }
}
