//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_WMP_CFP
    {
        public short ISVALID { get; set; }
        public long INNER_CODE { get; set; }
        public Nullable<System.DateTime> DECLAREDATE { get; set; }
        public string CFPNAME { get; set; }
        public string CFPSNAME { get; set; }
        public string CFP_CODE { get; set; }
        public string ISIN { get; set; }
        public string CFP_TYPE { get; set; }
        public string PROD_TYPE_NAME { get; set; }
        public string INVEST_TARGET { get; set; }
        public string INVEST_TENET { get; set; }
        public string INVEST_RANGE { get; set; }
        public string INVEST_BENCH { get; set; }
        public string INVEST_STRA { get; set; }
        public string PERFORM_BENCH { get; set; }
        public string PROD_CHAR { get; set; }
        public Nullable<decimal> OBJ_VAL1 { get; set; }
        public Nullable<decimal> OBJ_VAL2 { get; set; }
        public Nullable<decimal> PERIOD { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<decimal> LOWEST_VAL { get; set; }
        public string LOWEST_VAL_CODE { get; set; }
        public string LOWEST_VAL_NAME { get; set; }
        public string INVEST_CLS { get; set; }
        public string INVEST_NAME { get; set; }
        public Nullable<System.DateTime> ESTAB_DATE { get; set; }
        public Nullable<decimal> TOT_VAL { get; set; }
        public string FORE_YIELD { get; set; }
        public string OPEN_PRD { get; set; }
        public string INV_MNG { get; set; }
        public string FIN_CYC { get; set; }
        public Nullable<System.DateTime> EXPE_ENDDATE { get; set; }
        public Nullable<System.DateTime> ACTU_ENDDATE { get; set; }
        public Nullable<decimal> ADD_UNIT_LOW { get; set; }
        public Nullable<decimal> QUIT_UNIT_LOW { get; set; }
        public Nullable<decimal> DURATION_SIZE_LOW { get; set; }
        public string CLOSED_PERD { get; set; }
        public string HUGE_QUIT_TERM { get; set; }
        public Nullable<decimal> IS_QDII { get; set; }
        public string IS_QDII_NAME { get; set; }
        public Nullable<decimal> ORGCODE { get; set; }
        public string ORGNAME { get; set; }
        public Nullable<decimal> MAG_ORGCODE { get; set; }
        public string MAG_ORGNAME { get; set; }
        public Nullable<long> ISS_STATUS { get; set; }
        public Nullable<decimal> UNT_NET { get; set; }
        public Nullable<decimal> UNT_ACCUM_NET { get; set; }
        public Nullable<decimal> WEEK_GR { get; set; }
        public Nullable<decimal> MONTH_GR { get; set; }
        public Nullable<decimal> ANNU_GR { get; set; }
        public Nullable<decimal> BUILD_ANNU_GR { get; set; }
        public Nullable<System.DateTime> CHNG_DATE { get; set; }
        public string PROD_STATE_CODE { get; set; }
        public string PROD_STATE { get; set; }
        public System.DateTime MTIME { get; set; }
    }
}
