//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZCXEntities : DbContext
    {
        public ZCXEntities()
            : base("name=ZCXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BOND_ISS_INFO> BOND_ISS_INFO { get; set; }
        public DbSet<BOND_RATE_INFO> BOND_RATE_INFO { get; set; }
        public DbSet<PUB_AREA_CODE> PUB_AREA_CODE { get; set; }
        public DbSet<PUB_CURY_TYPE> PUB_CURY_TYPE { get; set; }
        public DbSet<PUB_ORG_INFO> PUB_ORG_INFO { get; set; }
        public DbSet<PUB_PAR> PUB_PAR { get; set; }
        public DbSet<RATE_ORG_INFO_F> RATE_ORG_INFO_F { get; set; }
        public DbSet<RATE_REP> RATE_REP { get; set; }
        public DbSet<FUNDAMENTALFIELDMAPPING> FUNDAMENTALFIELDMAPPING { get; set; }
        public DbSet<BOND_BASIC_INFO> BOND_BASIC_INFO { get; set; }
        public DbSet<V_BOND_ABS> V_BOND_ABS { get; set; }
        public DbSet<BOND_ISSER_INFO> BOND_ISSER_INFO { get; set; }
        public DbSet<BOND_FIN_BALA_TABB> BOND_FIN_BALA_TABB { get; set; }
        public DbSet<BOND_FIN_CASH_TACB> BOND_FIN_CASH_TACB { get; set; }
        public DbSet<BOND_FIN_PROF_TAPB> BOND_FIN_PROF_TAPB { get; set; }
        public DbSet<BOND_SIZE_CHAN> BOND_SIZE_CHAN { get; set; }
    }
}
