//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNE.Scheduler.SXCoal {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="data", ConfigurationName="SXCoal.web_dataSoap")]
    public interface web_dataSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="data/GetData_LutouDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetData_LutouDetail(string updateDate, string pass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface web_dataSoapChannel : CNE.Scheduler.SXCoal.web_dataSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class web_dataSoapClient : System.ServiceModel.ClientBase<CNE.Scheduler.SXCoal.web_dataSoap>, CNE.Scheduler.SXCoal.web_dataSoap {
        
        public web_dataSoapClient() {
        }
        
        public web_dataSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public web_dataSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public web_dataSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public web_dataSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetData_LutouDetail(string updateDate, string pass) {
            return base.Channel.GetData_LutouDetail(updateDate, pass);
        }
    }
}
