//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNE.Scheduler.CenterService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.service.data.com/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.service.data.com/")]
    public partial class authorization : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string passwordField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.service.data.com/")]
    public partial class FileNotFoundException : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://server.service.data.com/", ConfigurationName="CenterService.DataCenterMTOMVerifyService")]
    public interface DataCenterMTOMVerifyService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CNE.Scheduler.CenterService.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CNE.Scheduler.CenterService.dataSetFailResponse dataSetFail(CNE.Scheduler.CenterService.dataSetFail request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CNE.Scheduler.CenterService.Exception), Action="", Name="Exception")]
        [System.ServiceModel.FaultContractAttribute(typeof(CNE.Scheduler.CenterService.FileNotFoundException), Action="", Name="FileNotFoundException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CNE.Scheduler.CenterService.getTargetsResponse getTargets(CNE.Scheduler.CenterService.getTargets request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CNE.Scheduler.CenterService.Exception), Action="", Name="Exception")]
        [System.ServiceModel.FaultContractAttribute(typeof(CNE.Scheduler.CenterService.FileNotFoundException), Action="", Name="FileNotFoundException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CNE.Scheduler.CenterService.getDataSetResponse getDataSet(CNE.Scheduler.CenterService.getDataSet request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CNE.Scheduler.CenterService.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CNE.Scheduler.CenterService.registerResponse register(CNE.Scheduler.CenterService.register request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dataSetFail", WrapperNamespace="http://server.service.data.com/", IsWrapped=true)]
    public partial class dataSetFail {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.service.data.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long userOptionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.service.data.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CNE.Scheduler.CenterService.authorization authorization;
        
        public dataSetFail() {
        }
        
        public dataSetFail(long userOptionID, CNE.Scheduler.CenterService.authorization authorization) {
            this.userOptionID = userOptionID;
            this.authorization = authorization;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dataSetFailResponse", WrapperNamespace="http://server.service.data.com/", IsWrapped=true)]
    public partial class dataSetFailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.service.data.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public dataSetFailResponse() {
        }
        
        public dataSetFailResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTargets", WrapperNamespace="http://server.service.data.com/", IsWrapped=true)]
    public partial class getTargets {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.service.data.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CNE.Scheduler.CenterService.authorization authorization;
        
        public getTargets() {
        }
        
        public getTargets(CNE.Scheduler.CenterService.authorization authorization) {
            this.authorization = authorization;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTargetsResponse", WrapperNamespace="http://server.service.data.com/", IsWrapped=true)]
    public partial class getTargetsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.service.data.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] @return;
        
        public getTargetsResponse() {
        }
        
        public getTargetsResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataSet", WrapperNamespace="http://server.service.data.com/", IsWrapped=true)]
    public partial class getDataSet {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.service.data.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resourceID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.service.data.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CNE.Scheduler.CenterService.authorization authorization;
        
        public getDataSet() {
        }
        
        public getDataSet(string resourceID, CNE.Scheduler.CenterService.authorization authorization) {
            this.resourceID = resourceID;
            this.authorization = authorization;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataSetResponse", WrapperNamespace="http://server.service.data.com/", IsWrapped=true)]
    public partial class getDataSetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.service.data.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] @return;
        
        public getDataSetResponse() {
        }
        
        public getDataSetResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="register", WrapperNamespace="http://server.service.data.com/", IsWrapped=true)]
    public partial class register {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.service.data.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CNE.Scheduler.CenterService.authorization authorization;
        
        public register() {
        }
        
        public register(CNE.Scheduler.CenterService.authorization authorization) {
            this.authorization = authorization;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registerResponse", WrapperNamespace="http://server.service.data.com/", IsWrapped=true)]
    public partial class registerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.service.data.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public registerResponse() {
        }
        
        public registerResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataCenterMTOMVerifyServiceChannel : CNE.Scheduler.CenterService.DataCenterMTOMVerifyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataCenterMTOMVerifyServiceClient : System.ServiceModel.ClientBase<CNE.Scheduler.CenterService.DataCenterMTOMVerifyService>, CNE.Scheduler.CenterService.DataCenterMTOMVerifyService {
        
        public DataCenterMTOMVerifyServiceClient() {
        }
        
        public DataCenterMTOMVerifyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataCenterMTOMVerifyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataCenterMTOMVerifyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataCenterMTOMVerifyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CNE.Scheduler.CenterService.dataSetFailResponse CNE.Scheduler.CenterService.DataCenterMTOMVerifyService.dataSetFail(CNE.Scheduler.CenterService.dataSetFail request) {
            return base.Channel.dataSetFail(request);
        }
        
        public string dataSetFail(long userOptionID, CNE.Scheduler.CenterService.authorization authorization) {
            CNE.Scheduler.CenterService.dataSetFail inValue = new CNE.Scheduler.CenterService.dataSetFail();
            inValue.userOptionID = userOptionID;
            inValue.authorization = authorization;
            CNE.Scheduler.CenterService.dataSetFailResponse retVal = ((CNE.Scheduler.CenterService.DataCenterMTOMVerifyService)(this)).dataSetFail(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CNE.Scheduler.CenterService.getTargetsResponse CNE.Scheduler.CenterService.DataCenterMTOMVerifyService.getTargets(CNE.Scheduler.CenterService.getTargets request) {
            return base.Channel.getTargets(request);
        }
        
        public byte[] getTargets(CNE.Scheduler.CenterService.authorization authorization) {
            CNE.Scheduler.CenterService.getTargets inValue = new CNE.Scheduler.CenterService.getTargets();
            inValue.authorization = authorization;
            CNE.Scheduler.CenterService.getTargetsResponse retVal = ((CNE.Scheduler.CenterService.DataCenterMTOMVerifyService)(this)).getTargets(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CNE.Scheduler.CenterService.getDataSetResponse CNE.Scheduler.CenterService.DataCenterMTOMVerifyService.getDataSet(CNE.Scheduler.CenterService.getDataSet request) {
            return base.Channel.getDataSet(request);
        }
        
        public byte[] getDataSet(string resourceID, CNE.Scheduler.CenterService.authorization authorization) {
            CNE.Scheduler.CenterService.getDataSet inValue = new CNE.Scheduler.CenterService.getDataSet();
            inValue.resourceID = resourceID;
            inValue.authorization = authorization;
            CNE.Scheduler.CenterService.getDataSetResponse retVal = ((CNE.Scheduler.CenterService.DataCenterMTOMVerifyService)(this)).getDataSet(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CNE.Scheduler.CenterService.registerResponse CNE.Scheduler.CenterService.DataCenterMTOMVerifyService.register(CNE.Scheduler.CenterService.register request) {
            return base.Channel.register(request);
        }
        
        public string register(CNE.Scheduler.CenterService.authorization authorization) {
            CNE.Scheduler.CenterService.register inValue = new CNE.Scheduler.CenterService.register();
            inValue.authorization = authorization;
            CNE.Scheduler.CenterService.registerResponse retVal = ((CNE.Scheduler.CenterService.DataCenterMTOMVerifyService)(this)).register(inValue);
            return retVal.@return;
        }
    }
}
