//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CnE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CnE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CnE", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 供需平衡表.
        /// </summary>
        internal static string CNE_BalanceTable {
            get {
                return ResourceManager.GetString("CNE_BalanceTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string CNE_Region {
            get {
                return ResourceManager.GetString("CNE_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Capability (10K ton).
        /// </summary>
        internal static string CNE_SdR_DailyOutputCapacity {
            get {
                return ResourceManager.GetString("CNE_SdR_DailyOutputCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string CNE_SdR_DailyOutputDate {
            get {
                return ResourceManager.GetString("CNE_SdR_DailyOutputDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesel（ton）.
        /// </summary>
        internal static string CNE_SdR_DailyOutputDiesel {
            get {
                return ResourceManager.GetString("CNE_SdR_DailyOutputDiesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasoline（ton）.
        /// </summary>
        internal static string CNE_SdR_DailyOutputGasoline {
            get {
                return ResourceManager.GetString("CNE_SdR_DailyOutputGasoline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Output.
        /// </summary>
        internal static string CNE_SdR_DailyOutputTitle {
            get {
                return ResourceManager.GetString("CNE_SdR_DailyOutputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string CNE_SdR_Device {
            get {
                return ResourceManager.GetString("CNE_SdR_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Detail.
        /// </summary>
        internal static string CNE_SdR_DeviceTitle {
            get {
                return ResourceManager.GetString("CNE_SdR_DeviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        internal static string CNE_SdR_DeviceUpdate {
            get {
                return ResourceManager.GetString("CNE_SdR_DeviceUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10Kton.
        /// </summary>
        internal static string CNE_SdR_DeviceYieldByTon {
            get {
                return ResourceManager.GetString("CNE_SdR_DeviceYieldByTon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refinery.
        /// </summary>
        internal static string CNE_SdR_Refinery {
            get {
                return ResourceManager.GetString("CNE_SdR_Refinery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrels/Day.
        /// </summary>
        internal static string CNE_SdR_YieldByBarrel {
            get {
                return ResourceManager.GetString("CNE_SdR_YieldByBarrel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shandong Local Refinery.
        /// </summary>
        internal static string CNE_ShangDonLocalRefinery {
            get {
                return ResourceManager.GetString("CNE_ShangDonLocalRefinery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNY/Tonne.
        /// </summary>
        internal static string CNYTonne {
            get {
                return ResourceManager.GetString("CNYTonne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lignite Arrivals(Wagon).
        /// </summary>
        internal static string Coal_BrownCoal {
            get {
                return ResourceManager.GetString("Coal_BrownCoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The port of coal mine.
        /// </summary>
        internal static string Coal_Schedular {
            get {
                return ResourceManager.GetString("Coal_Schedular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessels Anchored(Vessel).
        /// </summary>
        internal static string Coal_Traffic_Anchor {
            get {
                return ResourceManager.GetString("Coal_Traffic_Anchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessels Expected(Vessel).
        /// </summary>
        internal static string Coal_Traffic_Anchor_Num {
            get {
                return ResourceManager.GetString("Coal_Traffic_Anchor_Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment(10000 MT).
        /// </summary>
        internal static string Coal_Traffic_Boat {
            get {
                return ResourceManager.GetString("Coal_Traffic_Boat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rail Cars Unloaded(Wagon).
        /// </summary>
        internal static string Coal_Traffic_DayNight_Track {
            get {
                return ResourceManager.GetString("Coal_Traffic_DayNight_Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock(10000 MT).
        /// </summary>
        internal static string Coal_Traffic_Filed {
            get {
                return ResourceManager.GetString("Coal_Traffic_Filed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Frequency.
        /// </summary>
        internal static string Coal_Traffic_Frequency {
            get {
                return ResourceManager.GetString("Coal_Traffic_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rail Volume Unloaded(10000 MT).
        /// </summary>
        internal static string Coal_Traffic_Num {
            get {
                return ResourceManager.GetString("Coal_Traffic_Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berth(Vessel).
        /// </summary>
        internal static string Coal_Traffic_Park {
            get {
                return ResourceManager.GetString("Coal_Traffic_Park", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string Coal_Traffic_Port {
            get {
                return ResourceManager.GetString("Coal_Traffic_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rail Cars Arrivals(Wagon).
        /// </summary>
        internal static string Coal_Traffic_RailCar {
            get {
                return ResourceManager.GetString("Coal_Traffic_RailCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rail Inflow(10000 MT).
        /// </summary>
        internal static string Coal_Traffic_Railway {
            get {
                return ResourceManager.GetString("Coal_Traffic_Railway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road Inflow(10000 MT).
        /// </summary>
        internal static string Coal_Traffic_Road {
            get {
                return ResourceManager.GetString("Coal_Traffic_Road", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rail Cars Unloaded(car).
        /// </summary>
        internal static string Coal_Traffic_Track {
            get {
                return ResourceManager.GetString("Coal_Traffic_Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throughput(10000 MT).
        /// </summary>
        internal static string Coal_Traffic_Trough {
            get {
                return ResourceManager.GetString("Coal_Traffic_Trough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit:10000 MT.
        /// </summary>
        internal static string Coal_Unit {
            get {
                return ResourceManager.GetString("Coal_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesel.
        /// </summary>
        internal static string Diesel {
            get {
                return ResourceManager.GetString("Diesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasoline.
        /// </summary>
        internal static string Gasoline {
            get {
                return ResourceManager.GetString("Gasoline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string GDT_ChartInventoryName {
            get {
                return ResourceManager.GetString("GDT_ChartInventoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string GDT_ChartOuputName {
            get {
                return ResourceManager.GetString("GDT_ChartOuputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string GDT_ChartSalesName {
            get {
                return ResourceManager.GetString("GDT_ChartSalesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:Fanya, Thomson Reuters.
        /// </summary>
        internal static string GDT_FanyaSource {
            get {
                return ResourceManager.GetString("GDT_FanyaSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Table.
        /// </summary>
        internal static string GDT_InventoryTitle {
            get {
                return ResourceManager.GetString("GDT_InventoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NBS do not publish industrial data of January.
        /// </summary>
        internal static string GDT_NBS_Statement {
            get {
                return ResourceManager.GetString("GDT_NBS_Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Table.
        /// </summary>
        internal static string GDT_OutputTitle {
            get {
                return ResourceManager.GetString("GDT_OutputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price AVG.
        /// </summary>
        internal static string GDT_PriceChartPriceAvgName {
            get {
                return ResourceManager.GetString("GDT_PriceChartPriceAvgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string GDT_PriceChartPriceName {
            get {
                return ResourceManager.GetString("GDT_PriceChartPriceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL.
        /// </summary>
        internal static string GDT_PriceChart_ {
            get {
                return ResourceManager.GetString("GDT_PriceChart_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Spline.
        /// </summary>
        internal static string GDT_PriceTitle {
            get {
                return ResourceManager.GetString("GDT_PriceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Table.
        /// </summary>
        internal static string GDT_SalesTitle {
            get {
                return ResourceManager.GetString("GDT_SalesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:Shanghai Shipping Freight Exchange Co., Ltd.,Thomson Reuters.
        /// </summary>
        internal static string GDT_ShippingSource {
            get {
                return ResourceManager.GetString("GDT_ShippingSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplyDemandItem.
        /// </summary>
        internal static string GDT_SupplyDemandItem {
            get {
                return ResourceManager.GetString("GDT_SupplyDemandItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplyDemandBallanceTable.
        /// </summary>
        internal static string GDT_SupplyDemandTable {
            get {
                return ResourceManager.GetString("GDT_SupplyDemandTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        internal static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        internal static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Capacity Rate.
        /// </summary>
        internal static string StockCapacityRate {
            get {
                return ResourceManager.GetString("StockCapacityRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuation.
        /// </summary>
        internal static string Valuation {
            get {
                return ResourceManager.GetString("Valuation", resourceCulture);
            }
        }
    }
}
