//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IPP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IPP() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.IPP", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver list should be less than {1} charactors..
        /// </summary>
        internal static string ApproverLengthMessage {
            get {
                return ResourceManager.GetString("ApproverLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author should be less than {1} charactors..
        /// </summary>
        internal static string AuthorLengthMessage {
            get {
                return ResourceManager.GetString("AuthorLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author RM should be less than {1} charactors..
        /// </summary>
        internal static string AuthorRMLengthMessage {
            get {
                return ResourceManager.GetString("AuthorRMLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Email Address..
        /// </summary>
        internal static string EmailAddressValidation {
            get {
                return ResourceManager.GetString("EmailAddressValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Edit/Delete.
        /// </summary>
        internal static string IPP_Allow_Edit_Delete {
            get {
                return ResourceManager.GetString("IPP_Allow_Edit_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already approved by other approver..
        /// </summary>
        internal static string IPP_Already_Approve {
            get {
                return ResourceManager.GetString("IPP_Already_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcement.
        /// </summary>
        internal static string IPP_Announcement {
            get {
                return ResourceManager.GetString("IPP_Announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string IPP_Approved {
            get {
                return ResourceManager.GetString("IPP_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string IPP_Approveds {
            get {
                return ResourceManager.GetString("IPP_Approveds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver.
        /// </summary>
        internal static string IPP_Approver {
            get {
                return ResourceManager.GetString("IPP_Approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approvers.
        /// </summary>
        internal static string IPP_Approvers {
            get {
                return ResourceManager.GetString("IPP_Approvers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string IPP_Author {
            get {
                return ResourceManager.GetString("IPP_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auhtor Email.
        /// </summary>
        internal static string IPP_Author_Email {
            get {
                return ResourceManager.GetString("IPP_Author_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author RM.
        /// </summary>
        internal static string IPP_Author_Rm {
            get {
                return ResourceManager.GetString("IPP_Author_Rm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string IPP_Available {
            get {
                return ResourceManager.GetString("IPP_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking List.
        /// </summary>
        internal static string IPP_BillBoard {
            get {
                return ResourceManager.GetString("IPP_BillBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancle.
        /// </summary>
        internal static string IPP_Cancle {
            get {
                return ResourceManager.GetString("IPP_Cancle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic chat room.
        /// </summary>
        internal static string IPP_Chatroom {
            get {
                return ResourceManager.GetString("IPP_Chatroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creater.
        /// </summary>
        internal static string IPP_Creater {
            get {
                return ResourceManager.GetString("IPP_Creater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Date.
        /// </summary>
        internal static string IPP_Create_Date {
            get {
                return ResourceManager.GetString("IPP_Create_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create topic.
        /// </summary>
        internal static string IPP_Create_Topic {
            get {
                return ResourceManager.GetString("IPP_Create_Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string IPP_Delete {
            get {
                return ResourceManager.GetString("IPP_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string IPP_Descr {
            get {
                return ResourceManager.GetString("IPP_Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Description.
        /// </summary>
        internal static string IPP_Desc_Cn {
            get {
                return ResourceManager.GetString("IPP_Desc_Cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Description.
        /// </summary>
        internal static string IPP_Desc_En {
            get {
                return ResourceManager.GetString("IPP_Desc_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string IPP_Edit {
            get {
                return ResourceManager.GetString("IPP_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string IPP_File {
            get {
                return ResourceManager.GetString("IPP_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete, file exists in the current topic..
        /// </summary>
        internal static string IPP_FileExist {
            get {
                return ResourceManager.GetString("IPP_FileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file upload is required..
        /// </summary>
        internal static string IPP_File_Not_Null {
            get {
                return ResourceManager.GetString("IPP_File_Not_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File should be less that 5M..
        /// </summary>
        internal static string IPP_File_Size_Alert {
            get {
                return ResourceManager.GetString("IPP_File_Size_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        internal static string IPP_Follow {
            get {
                return ResourceManager.GetString("IPP_Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto topic.
        /// </summary>
        internal static string IPP_Goto_Topic {
            get {
                return ResourceManager.GetString("IPP_Goto_Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hits.
        /// </summary>
        internal static string IPP_Hit {
            get {
                return ResourceManager.GetString("IPP_Hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Topic.
        /// </summary>
        internal static string IPP_HotTopic {
            get {
                return ResourceManager.GetString("IPP_HotTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need approve.
        /// </summary>
        internal static string IPP_If_Need_Approve {
            get {
                return ResourceManager.GetString("IPP_If_Need_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Approve(Internal).
        /// </summary>
        internal static string IPP_Internal_Need_Approve {
            get {
                return ResourceManager.GetString("IPP_Internal_Need_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is following.
        /// </summary>
        internal static string IPP_IsFollowing {
            get {
                return ResourceManager.GetString("IPP_IsFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Latest.
        /// </summary>
        internal static string IPP_Latest {
            get {
                return ResourceManager.GetString("IPP_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest 1 Month.
        /// </summary>
        internal static string IPP_Latest1M {
            get {
                return ResourceManager.GetString("IPP_Latest1M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest 1 Week.
        /// </summary>
        internal static string IPP_Latest1W {
            get {
                return ResourceManager.GetString("IPP_Latest1W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest 2 Week.
        /// </summary>
        internal static string IPP_Latest2W {
            get {
                return ResourceManager.GetString("IPP_Latest2W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest 3 Month.
        /// </summary>
        internal static string IPP_Latest3M {
            get {
                return ResourceManager.GetString("IPP_Latest3M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        internal static string IPP_Module {
            get {
                return ResourceManager.GetString("IPP_Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Document.
        /// </summary>
        internal static string IPP_MyDocument {
            get {
                return ResourceManager.GetString("IPP_MyDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Favorite.
        /// </summary>
        internal static string IPP_MyFavorite {
            get {
                return ResourceManager.GetString("IPP_MyFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Approve.
        /// </summary>
        internal static string IPP_Need_Approve {
            get {
                return ResourceManager.GetString("IPP_Need_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string IPP_No {
            get {
                return ResourceManager.GetString("IPP_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        internal static string IPP_Operation {
            get {
                return ResourceManager.GetString("IPP_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Approve.
        /// </summary>
        internal static string IPP_PendingApprove {
            get {
                return ResourceManager.GetString("IPP_PendingApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persons.
        /// </summary>
        internal static string IPP_Persons {
            get {
                return ResourceManager.GetString("IPP_Persons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Published.
        /// </summary>
        internal static string IPP_PrePublished {
            get {
                return ResourceManager.GetString("IPP_PrePublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        internal static string IPP_Publish {
            get {
                return ResourceManager.GetString("IPP_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Content.
        /// </summary>
        internal static string IPP_PublishContent {
            get {
                return ResourceManager.GetString("IPP_PublishContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        internal static string IPP_Published {
            get {
                return ResourceManager.GetString("IPP_Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish File.
        /// </summary>
        internal static string IPP_Publish_File {
            get {
                return ResourceManager.GetString("IPP_Publish_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string IPP_Query {
            get {
                return ResourceManager.GetString("IPP_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string IPP_QueryTopic {
            get {
                return ResourceManager.GetString("IPP_QueryTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string IPP_Rating {
            get {
                return ResourceManager.GetString("IPP_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating Stats.
        /// </summary>
        internal static string IPP_RatingStats {
            get {
                return ResourceManager.GetString("IPP_RatingStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string IPP_Rejected {
            get {
                return ResourceManager.GetString("IPP_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIKON RIC.
        /// </summary>
        internal static string IPP_Ric {
            get {
                return ResourceManager.GetString("IPP_Ric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIKON RIC-Chart.
        /// </summary>
        internal static string IPP_Ric_Chart {
            get {
                return ResourceManager.GetString("IPP_Ric_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIKON RIC-News.
        /// </summary>
        internal static string IPP_Ric_News {
            get {
                return ResourceManager.GetString("IPP_Ric_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIC is required..
        /// </summary>
        internal static string IPP_RIC_Not_Null {
            get {
                return ResourceManager.GetString("IPP_RIC_Not_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIKON RIC-Quote.
        /// </summary>
        internal static string IPP_Ric_Quote {
            get {
                return ResourceManager.GetString("IPP_Ric_Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EIKON RIC-QuoteList.
        /// </summary>
        internal static string IPP_Ric_QuoteList {
            get {
                return ResourceManager.GetString("IPP_Ric_QuoteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIC Type.
        /// </summary>
        internal static string IPP_Ric_Type {
            get {
                return ResourceManager.GetString("IPP_Ric_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM Link.
        /// </summary>
        internal static string IPP_RMLink {
            get {
                return ResourceManager.GetString("IPP_RMLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Room.
        /// </summary>
        internal static string IPP_RM_Link {
            get {
                return ResourceManager.GetString("IPP_RM_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string IPP_Save {
            get {
                return ResourceManager.GetString("IPP_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Site.
        /// </summary>
        internal static string IPP_Site {
            get {
                return ResourceManager.GetString("IPP_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string IPP_Source {
            get {
                return ResourceManager.GetString("IPP_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use semicolon if input muliptle tags.
        /// </summary>
        internal static string IPP_Sperator {
            get {
                return ResourceManager.GetString("IPP_Sperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star.
        /// </summary>
        internal static string IPP_Star {
            get {
                return ResourceManager.GetString("IPP_Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string IPP_Status {
            get {
                return ResourceManager.GetString("IPP_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string IPP_Submit {
            get {
                return ResourceManager.GetString("IPP_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitter.
        /// </summary>
        internal static string IPP_Submiter {
            get {
                return ResourceManager.GetString("IPP_Submiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Date.
        /// </summary>
        internal static string IPP_Submit_Date {
            get {
                return ResourceManager.GetString("IPP_Submit_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string IPP_Tag {
            get {
                return ResourceManager.GetString("IPP_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail.
        /// </summary>
        internal static string IPP_thumbnail {
            get {
                return ResourceManager.GetString("IPP_thumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string IPP_Title {
            get {
                return ResourceManager.GetString("IPP_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Title.
        /// </summary>
        internal static string IPP_Title_Cn {
            get {
                return ResourceManager.GetString("IPP_Title_Cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Chinese Title Is Required..
        /// </summary>
        internal static string IPP_Title_Cn_Val {
            get {
                return ResourceManager.GetString("IPP_Title_Cn_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Title.
        /// </summary>
        internal static string IPP_Title_En {
            get {
                return ResourceManager.GetString("IPP_Title_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The English Title Is Required..
        /// </summary>
        internal static string IPP_Title_En_Val {
            get {
                return ResourceManager.GetString("IPP_Title_En_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string IPP_To {
            get {
                return ResourceManager.GetString("IPP_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top hits.
        /// </summary>
        internal static string IPP_TopHits {
            get {
                return ResourceManager.GetString("IPP_TopHits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        internal static string IPP_Topic {
            get {
                return ResourceManager.GetString("IPP_Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic Management.
        /// </summary>
        internal static string IPP_TopicManagement {
            get {
                return ResourceManager.GetString("IPP_TopicManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic description.
        /// </summary>
        internal static string IPP_Topic_Desc {
            get {
                return ResourceManager.GetString("IPP_Topic_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic name.
        /// </summary>
        internal static string IPP_Topic_Name {
            get {
                return ResourceManager.GetString("IPP_Topic_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfollow.
        /// </summary>
        internal static string IPP_UnFollow {
            get {
                return ResourceManager.GetString("IPP_UnFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Create/Edit.
        /// </summary>
        internal static string IPP_Uplaod_Header {
            get {
                return ResourceManager.GetString("IPP_Uplaod_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic Create/Edit.
        /// </summary>
        internal static string IPP_Uplaod_Topic_Header {
            get {
                return ResourceManager.GetString("IPP_Uplaod_Topic_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string IPP_Upload {
            get {
                return ResourceManager.GetString("IPP_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Type.
        /// </summary>
        internal static string IPP_Upload_Type {
            get {
                return ResourceManager.GetString("IPP_Upload_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string IPP_Website {
            get {
                return ResourceManager.GetString("IPP_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web site is required..
        /// </summary>
        internal static string IPP_WebSite_Not_Null {
            get {
                return ResourceManager.GetString("IPP_WebSite_Not_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string IPP_Yes {
            get {
                return ResourceManager.GetString("IPP_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM link should be less than {1} charactors..
        /// </summary>
        internal static string RMLinkLengthMessage {
            get {
                return ResourceManager.GetString("RMLinkLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitter should be less than {1} charactors..
        /// </summary>
        internal static string SubmiterLengthMessage {
            get {
                return ResourceManager.GetString("SubmiterLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag should be less than {1} charactors..
        /// </summary>
        internal static string TagLengthMessage {
            get {
                return ResourceManager.GetString("TagLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Title should be less than {1} charactors..
        /// </summary>
        internal static string TitleCnLengthMessage {
            get {
                return ResourceManager.GetString("TitleCnLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Title should be less than {1} charactors..
        /// </summary>
        internal static string TitleEnLengthMessage {
            get {
                return ResourceManager.GetString("TitleEnLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placed at the top.
        /// </summary>
        internal static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
    }
}
