//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WMP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WMP() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.WMP", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulated Net Growth Rate(%).
        /// </summary>
        internal static string Broker_Accumulated_Net_Growth_Rate {
            get {
                return ResourceManager.GetString("Broker_Accumulated_Net_Growth_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulated Net Value.
        /// </summary>
        internal static string Broker_Accumulated_Net_Value {
            get {
                return ResourceManager.GetString("Broker_Accumulated_Net_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maturity Date.
        /// </summary>
        internal static string Broker_ACTU_ENDDATE {
            get {
                return ResourceManager.GetString("Broker_ACTU_ENDDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Additional Amount(10k).
        /// </summary>
        internal static string Broker_ADD_UNIT_LOW {
            get {
                return ResourceManager.GetString("Broker_ADD_UNIT_LOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management&apos;s Participation Size.
        /// </summary>
        internal static string Broker_ADMN_VAL {
            get {
                return ResourceManager.GetString("Broker_ADMN_VAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of Purchase.
        /// </summary>
        internal static string Broker_Amount_of_Purchase {
            get {
                return ResourceManager.GetString("Broker_Amount_of_Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcement Name.
        /// </summary>
        internal static string Broker_Announcement_Name {
            get {
                return ResourceManager.GetString("Broker_Announcement_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annualized Yield.
        /// </summary>
        internal static string Broker_Annual_Yield {
            get {
                return ResourceManager.GetString("Broker_Annual_Yield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Value.
        /// </summary>
        internal static string Broker_BOOK_VAL {
            get {
                return ResourceManager.GetString("Broker_BOOK_VAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Full Name.
        /// </summary>
        internal static string Broker_CFPNAME {
            get {
                return ResourceManager.GetString("Broker_CFPNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Abbreviation.
        /// </summary>
        internal static string Broker_CFPSNAME {
            get {
                return ResourceManager.GetString("Broker_CFPSNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan ID.
        /// </summary>
        internal static string Broker_CFP_CODE {
            get {
                return ResourceManager.GetString("Broker_CFP_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Identification.
        /// </summary>
        internal static string Broker_CFP_ID {
            get {
                return ResourceManager.GetString("Broker_CFP_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        internal static string Broker_CFP_TYPE {
            get {
                return ResourceManager.GetString("Broker_CFP_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method of Share Settlement or Assignment.
        /// </summary>
        internal static string Broker_CF_MODE {
            get {
                return ResourceManager.GetString("Broker_CF_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock-up Period.
        /// </summary>
        internal static string Broker_CLOSED_PERD {
            get {
                return ResourceManager.GetString("Broker_CLOSED_PERD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Growth.
        /// </summary>
        internal static string Broker_Daily_Growth {
            get {
                return ResourceManager.GetString("Broker_Daily_Growth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcement Date.
        /// </summary>
        internal static string Broker_DECLAREDATE {
            get {
                return ResourceManager.GetString("Broker_DECLAREDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Target.
        /// </summary>
        internal static string Broker_Distribution_Target {
            get {
                return ResourceManager.GetString("Broker_Distribution_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dividend.
        /// </summary>
        internal static string Broker_Dividend {
            get {
                return ResourceManager.GetString("Broker_Dividend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dividend Accounting Date.
        /// </summary>
        internal static string Broker_Dividend_Accounting_Date {
            get {
                return ResourceManager.GetString("Broker_Dividend_Accounting_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dividend Date.
        /// </summary>
        internal static string Broker_Dividend_Date {
            get {
                return ResourceManager.GetString("Broker_Dividend_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dividend(Yuan/Unit).
        /// </summary>
        internal static string Broker_Dividend_Unit {
            get {
                return ResourceManager.GetString("Broker_Dividend_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsequent Minimum.
        /// </summary>
        internal static string Broker_DURATION_SIZE_LOW {
            get {
                return ResourceManager.GetString("Broker_DURATION_SIZE_LOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendation Closing Date.
        /// </summary>
        internal static string Broker_ENDDATE {
            get {
                return ResourceManager.GetString("Broker_ENDDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending Net Asset Value(10K).
        /// </summary>
        internal static string Broker_Ending_Net_Asset_Value {
            get {
                return ResourceManager.GetString("Broker_Ending_Net_Asset_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string Broker_End_Date {
            get {
                return ResourceManager.GetString("Broker_End_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Date.
        /// </summary>
        internal static string Broker_ESTAB_DATE {
            get {
                return ResourceManager.GetString("Broker_ESTAB_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Maturity Date.
        /// </summary>
        internal static string Broker_EXPE_ENDDATE {
            get {
                return ResourceManager.GetString("Broker_EXPE_ENDDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex-dividend Date.
        /// </summary>
        internal static string Broker_Ex_dividend_Date {
            get {
                return ResourceManager.GetString("Broker_Ex_dividend_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Indicator.
        /// </summary>
        internal static string Broker_Financial_Indicator {
            get {
                return ResourceManager.GetString("Broker_Financial_Indicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Cycle.
        /// </summary>
        internal static string Broker_FIN_CYC {
            get {
                return ResourceManager.GetString("Broker_FIN_CYC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Yield Description.
        /// </summary>
        internal static string Broker_FORE_YIELD {
            get {
                return ResourceManager.GetString("Broker_FORE_YIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holding Period.
        /// </summary>
        internal static string Broker_Holding_Period {
            get {
                return ResourceManager.GetString("Broker_Holding_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Redemption Identification.
        /// </summary>
        internal static string Broker_HUGE_QUIT_TERM {
            get {
                return ResourceManager.GetString("Broker_HUGE_QUIT_TERM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment Benchmark.
        /// </summary>
        internal static string Broker_INVEST_BENCH {
            get {
                return ResourceManager.GetString("Broker_INVEST_BENCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment Type.
        /// </summary>
        internal static string Broker_INVEST_CLS {
            get {
                return ResourceManager.GetString("Broker_INVEST_CLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment Scope.
        /// </summary>
        internal static string Broker_INVEST_RANGE {
            get {
                return ResourceManager.GetString("Broker_INVEST_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment Strategy.
        /// </summary>
        internal static string Broker_INVEST_STRA {
            get {
                return ResourceManager.GetString("Broker_INVEST_STRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment Traget.
        /// </summary>
        internal static string Broker_INVEST_TARGET {
            get {
                return ResourceManager.GetString("Broker_INVEST_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment Philosophy.
        /// </summary>
        internal static string Broker_INVEST_TENET {
            get {
                return ResourceManager.GetString("Broker_INVEST_TENET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Announcement.
        /// </summary>
        internal static string Broker_Issue_Announcement {
            get {
                return ResourceManager.GetString("Broker_Issue_Announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QDII.
        /// </summary>
        internal static string Broker_IS_QDII {
            get {
                return ResourceManager.GetString("Broker_IS_QDII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Amount.
        /// </summary>
        internal static string Broker_LOWEST_Amount {
            get {
                return ResourceManager.GetString("Broker_LOWEST_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Initial Investment(10k).
        /// </summary>
        internal static string Broker_LOWEST_VAL {
            get {
                return ResourceManager.GetString("Broker_LOWEST_VAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custodian Bank.
        /// </summary>
        internal static string Broker_MAG_ORG {
            get {
                return ResourceManager.GetString("Broker_MAG_ORG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Rate.
        /// </summary>
        internal static string Broker_Mag_Rate {
            get {
                return ResourceManager.GetString("Broker_Mag_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Growth Rate(%).
        /// </summary>
        internal static string Broker_Net_Growth_Rate {
            get {
                return ResourceManager.GetString("Broker_Net_Growth_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Value.
        /// </summary>
        internal static string Broker_Net_Worth {
            get {
                return ResourceManager.GetString("Broker_Net_Worth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History detail.
        /// </summary>
        internal static string Broker_Net_Worth_History {
            get {
                return ResourceManager.GetString("Broker_Net_Worth_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string Broker_Note {
            get {
                return ResourceManager.GetString("Broker_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Period.
        /// </summary>
        internal static string Broker_OPEN_PRD {
            get {
                return ResourceManager.GetString("Broker_OPEN_PRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regulatory Agency.
        /// </summary>
        internal static string Broker_Orgname {
            get {
                return ResourceManager.GetString("Broker_Orgname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Benchmark.
        /// </summary>
        internal static string Broker_PERFORM_BENCH {
            get {
                return ResourceManager.GetString("Broker_PERFORM_BENCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Rate.
        /// </summary>
        internal static string Broker_Product_Rate {
            get {
                return ResourceManager.GetString("Broker_Product_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Feature.
        /// </summary>
        internal static string Broker_PROD_CHAR {
            get {
                return ResourceManager.GetString("Broker_PROD_CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment Manager.
        /// </summary>
        internal static string Broker_PROD_Manager {
            get {
                return ResourceManager.GetString("Broker_PROD_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product State.
        /// </summary>
        internal static string Broker_PROD_STATE {
            get {
                return ResourceManager.GetString("Broker_PROD_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit of the Period(10K).
        /// </summary>
        internal static string Broker_Profit_of_Period {
            get {
                return ResourceManager.GetString("Broker_Profit_of_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Redemption.
        /// </summary>
        internal static string Broker_QUIT_UNIT_LOW {
            get {
                return ResourceManager.GetString("Broker_QUIT_UNIT_LOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string Broker_Rate {
            get {
                return ResourceManager.GetString("Broker_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate of Purchase.
        /// </summary>
        internal static string Broker_Rate_of_Purchase {
            get {
                return ResourceManager.GetString("Broker_Rate_of_Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redemption Amount.
        /// </summary>
        internal static string Broker_Redemption_Amount {
            get {
                return ResourceManager.GetString("Broker_Redemption_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redemption Rate.
        /// </summary>
        internal static string Broker_Redemption_Rate {
            get {
                return ResourceManager.GetString("Broker_Redemption_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        internal static string Broker_Registration_Date {
            get {
                return ResourceManager.GetString("Broker_Registration_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Source.
        /// </summary>
        internal static string Broker_Report_Source {
            get {
                return ResourceManager.GetString("Broker_Report_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendation Starting Date.
        /// </summary>
        internal static string Broker_STARTDATE {
            get {
                return ResourceManager.GetString("Broker_STARTDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Amount.
        /// </summary>
        internal static string Broker_Subscription_Amount {
            get {
                return ResourceManager.GetString("Broker_Subscription_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Rate.
        /// </summary>
        internal static string Broker_Subscription_Rate {
            get {
                return ResourceManager.GetString("Broker_Subscription_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Total Scale.
        /// </summary>
        internal static string Broker_TOT_VAL {
            get {
                return ResourceManager.GetString("Broker_TOT_VAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trustee Rate.
        /// </summary>
        internal static string Broker_Trustee_Rate {
            get {
                return ResourceManager.GetString("Broker_Trustee_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulated Net Value.
        /// </summary>
        internal static string Broker_UNT_ACCUM_NET {
            get {
                return ResourceManager.GetString("Broker_UNT_ACCUM_NET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Net Value.
        /// </summary>
        internal static string Broker_UNT_NET {
            get {
                return ResourceManager.GetString("Broker_UNT_NET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 days annualized rate.
        /// </summary>
        internal static string Seven_day_annualized_yield {
            get {
                return ResourceManager.GetString("Seven_day_annualized_yield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per ten thousands income.
        /// </summary>
        internal static string thousands_of_income {
            get {
                return ResourceManager.GetString("thousands_of_income", resourceCulture);
            }
        }
    }
}
