//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNEToolsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GETMAILLOG
    {
        public decimal? ID { get; set; }
        public System.DateTime GETMAILDATE { get; set; }
        public decimal STATUS { get; set; }
        public string DESCRIPTION { get; set; }
        public string JOBTYPE { get; set; }
    }
}
