//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAV.DAL.FileStorageService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://storage.cma.thomsonreuters.com/")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://storage.cma.thomsonreuters.com/")]
    public partial class fileEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] fileDataField;
        
        private string fileNameField;
        
        private string pathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] fileData {
            get {
                return this.fileDataField;
            }
            set {
                this.fileDataField = value;
                this.RaisePropertyChanged("fileData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
                this.RaisePropertyChanged("path");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://storage.cma.thomsonreuters.com/", ConfigurationName="FileStorageService.StorageService")]
    public interface StorageService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(VAV.DAL.FileStorageService.IOException), Action="", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        VAV.DAL.FileStorageService.AddFileObjResponse AddFileObj(VAV.DAL.FileStorageService.AddFileObj request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(VAV.DAL.FileStorageService.IOException), Action="", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        VAV.DAL.FileStorageService.RetriveFileObjResponse RetriveFileObj(VAV.DAL.FileStorageService.RetriveFileObj request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddFileObj", WrapperNamespace="http://storage.cma.thomsonreuters.com/", IsWrapped=true)]
    public partial class AddFileObj {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://storage.cma.thomsonreuters.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VAV.DAL.FileStorageService.fileEntity arg0;
        
        public AddFileObj() {
        }
        
        public AddFileObj(VAV.DAL.FileStorageService.fileEntity arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddFileObjResponse", WrapperNamespace="http://storage.cma.thomsonreuters.com/", IsWrapped=true)]
    public partial class AddFileObjResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://storage.cma.thomsonreuters.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public AddFileObjResponse() {
        }
        
        public AddFileObjResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetriveFileObj", WrapperNamespace="http://storage.cma.thomsonreuters.com/", IsWrapped=true)]
    public partial class RetriveFileObj {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://storage.cma.thomsonreuters.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://storage.cma.thomsonreuters.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public RetriveFileObj() {
        }
        
        public RetriveFileObj(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetriveFileObjResponse", WrapperNamespace="http://storage.cma.thomsonreuters.com/", IsWrapped=true)]
    public partial class RetriveFileObjResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://storage.cma.thomsonreuters.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VAV.DAL.FileStorageService.fileEntity @return;
        
        public RetriveFileObjResponse() {
        }
        
        public RetriveFileObjResponse(VAV.DAL.FileStorageService.fileEntity @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StorageServiceChannel : VAV.DAL.FileStorageService.StorageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StorageServiceClient : System.ServiceModel.ClientBase<VAV.DAL.FileStorageService.StorageService>, VAV.DAL.FileStorageService.StorageService {
        
        public StorageServiceClient() {
        }
        
        public StorageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StorageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StorageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StorageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VAV.DAL.FileStorageService.AddFileObjResponse VAV.DAL.FileStorageService.StorageService.AddFileObj(VAV.DAL.FileStorageService.AddFileObj request) {
            return base.Channel.AddFileObj(request);
        }
        
        public bool AddFileObj(VAV.DAL.FileStorageService.fileEntity arg0) {
            VAV.DAL.FileStorageService.AddFileObj inValue = new VAV.DAL.FileStorageService.AddFileObj();
            inValue.arg0 = arg0;
            VAV.DAL.FileStorageService.AddFileObjResponse retVal = ((VAV.DAL.FileStorageService.StorageService)(this)).AddFileObj(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VAV.DAL.FileStorageService.RetriveFileObjResponse VAV.DAL.FileStorageService.StorageService.RetriveFileObj(VAV.DAL.FileStorageService.RetriveFileObj request) {
            return base.Channel.RetriveFileObj(request);
        }
        
        public VAV.DAL.FileStorageService.fileEntity RetriveFileObj(string arg0, string arg1) {
            VAV.DAL.FileStorageService.RetriveFileObj inValue = new VAV.DAL.FileStorageService.RetriveFileObj();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            VAV.DAL.FileStorageService.RetriveFileObjResponse retVal = ((VAV.DAL.FileStorageService.StorageService)(this)).RetriveFileObj(inValue);
            return retVal.@return;
        }
    }
}
