//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNE.Scheduler.Extension.Model
{
    
    public partial class Factory
    {
        public int id { get; set; }
        public int x { get; set; }
        public int y { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string factoryName { get; set; }
        public string description { get; set; }
        public string displayName { get; set; }
        public string reserve1 { get; set; }
        public string reserve2 { get; set; }
        public string reserve3 { get; set; }
        public long updateDate { get; set; }
    }
}
